cloudfoundry/cf-acceptance-tests

services/init_test.go

When the CATs config file (eg. integration_config.json)
- have `cf_push_timeout` and
- does not have `broker_start_timeout`
`BROKER_START_TIMEOUT` will be set to _ZERO_.
This seems an unintentional behavior.

Fix unintentional overwrite of BROKER_START_TIMEOUT

---

README.md

Point the link to the bin/test script; not to the 'ensures that' word. 
Also 'test#L10-L15' in the link may not needed, 'test' is enough.

Update README.md - pointing to the correct bin/test script link.

---

apps/admin_buildpack_lifecycle_test.go
apps/app_bits_copy_test.go
apps/app_stack_test.go
apps/app_staging_environment_test.go
apps/buildpack_cache_test.go
apps/buildpacks_test.go
apps/changing_start_command_test.go
apps/delete_route_test.go
apps/droplet_download_test.go
apps/dynamic_info_test.go
apps/lifecycle_test.go
apps/loggregator_test.go
apps/one_push_many_restarts_test.go
apps/output_volume_test.go
apps/process_types_test.go
apps/staging_log_test.go
apps/wildcard_routes_test.go
helpers/services/broker.go
internet_dependent/git_buildpack_test.go
logging/syslog_drain_test.go
operator/environment_variables_group_test.go
operator/fuse_test.go
routing/routing_suite_test.go
security_groups/running_security_groups_test.go
services/purge_service_offering_test.go
services/recursive_delete_test.go
services/service_instance_lifecycle_test.go

Signed-off-by: Jesse Alford <jalford@pivotal.io>
we did the brute force method of decorating all `cf push` with `-m 128M` unless a -m flag was already present – a condition we checked for with manual review.
CATs passes on our environment with the following skip flags set
```
-skipPackage=helpers,v3,security_groups,routing '-skip=SSO|lucid64'
```
please consider merging this in for the cf-218 release.

reduce app memory usage to 128M unless previously specified

---

apps/large_payload_test.go
assets/dora/dora.rb

- Added an endpoint to the dora app, `/largetext`, that returns a response body of a specified size
- Added a test to the Applications CATs suite to test the return of a large response body from an app.

Add a large payload test to the Applications CATs suite

---

assets/dora/README.md

We added an endpoint to Dora for testing large payloads. This change simply adds the endpoint to the list of endpoints in the Dora readme.

Update dora README.md with information about /largetext endpoint

---

services/recursive_delete_test.go

The original `delete-quota` command here always fails because it is expecting interactive input to confirm the deletion. This commit supplies it with the `-f` flag to avoid the confirmation as well as the admin context authorizing it to perform the delete.

Clean up quota in recursive-delete services test

---

assets/dora/Gemfile
assets/fuse-mount/Gemfile
assets/service_broker/Gemfile

When Ruby versions get deprecated CATs start failing for the wrong reasons.
[#110323846]
Signed-off-by: Brandon Shroyer <bshroyer@pivotal.io>

remove `ruby` directives from Gemfile

---

routing/routing_suite_test.go

Use configured default and CF push timeouts in place of hardcoded values.

Override default and cf push timeouts if they are configured

---

cli_compatibility_test.go
routing/context_paths_test.go
routing/route_services_test.go
routing/routing_suite_test.go
routing/session_affinity_test.go

This PR updates CATS to use CF CLI for testing context route path.
Pivotal tracker story: https://www.pivotaltracker.com/story/show/106693894
Shash & Chris
Routing Team
Cloudfoundry

Update CATS to include context route path

---

helpers/v3_helpers/v3.go

Passing quotes to the form data parameter `-F` of curl, is only
supported from version 7.26 of curl (see
https://github.com/curl/curl/commit/2698520aef593cbd746a64f79021a4c8d7c83d65)
The latest stemcells include version 7.35, so the tests work fine in
a errand based on such stemcells, but if you run the test in a system
with an older version of curl (e.g. Debian stable with 7.26) the test
will fail.
This commit simply removes such quotes to allow run the test on older
versions or curl.

Do not pass quotes around filename for curl

---

v3/app_lifecycle_test.go
v3/buildpacks_test.go
v3/package_test.go
v3/process_test.go
v3/service_bindings_test.go
v3/task_test.go

Add protocol to uploadUrl in all of the v3 tests.
Tests fail without this if your deployment is operating on https instead of http. This is because without protocol specified the tests will try to connect using default protocol and port, which http on port 80.

Add protocol to uploadUrl of v3 tests

---

apps/loggregator_test.go

Firehose test was not failing when timeout was hit. It does fail now.
* An explanation of the use cases your change solves:
It properly fails now when timeout occurs, which is useful. This closes #94.

Allow firehose test to fail when it times out

---

ssh/ssh_test.go

Use a non-ephemeral port on linux (anything above 61000) for local port forwarding in the ssh cats.
* An explanation of the use cases your change solves
This fixes a race condition in which curl can allocate the same ephemeral port prior to the `cf ssh` command.
[#116934533]
Signed-off-by: James Myers <jmyers@pivotal.io>

Use non-ephemeral port for local port forwarding in ssh test

---

apps/loggregator_test.go

The reformat was due to moving the test under the correct context.
Check for errors from the firehose.
[##116437533]

Check for errors while slurping

---

apps/loggregator_test.go

We've been experiencing failures that look to be caused by the time to execute the tests are close to the timeouts. We were able to get consistent failures when we dropped the timeout to 15s which leads us to believe that most of the time, the tests are completing at close to the default timeout time span.
We ran this spec against an AWS deployment with the `ginkgo -untilItFails=true` twenty times without failure.

Increase timeoutes for firehose data tests

---

apps/lifecycle_test.go

Add a CAT to apps suite to cover pushing an app and starting multiple instances
* An explanation of the use cases your change solves
Tests multiple instances started when being pushed.
[#118940535]
Signed-off-by: Sandy Cash <scarlet.tanager@gmail.com>

add integration tests for starting multiple app instances

---

apps/buildpack_cache_test.go
apps/init_test.go
helpers/v3_helpers/globals.go
v3/buildpacks_test.go
v3/init_test.go

This PR changes `time.Sleep` to use `SleepTimeout` instead of `DefaultTimeout`. The CATS suite runs slow for us, so we need to use a high `DefaultTimeout`. Using `SleepTimeout` instead of `DefaultTimeout` lets us have the higher `DefaultTimeout` without sleeping for an unnecessary amount of time.

Use SleepTimeout instead of DefaultTimeout when sleeping

---

ssh/ssh_test.go

On linux the `0664` file permission will give write permission to the
current users group. When scping the file into a container, this
permission gets dropped as the group does not exist. On OSX, the group
is not given write permission to the generated file so this is not a
concern. On the errand VM, the vcap group exists in both the container
and the VM, so it is able to transfer the permissions correctly.
[#119334663]
* An explanation of the use cases your change solves
Running the cf-acceptance-tests locally on a linux workstation without the vcap user group.
Signed-off-by: James Myers <jmyers@pivotal.io>

Change file permissions of scp/sftp test asset

---

bin/test

[finishes #121014663]
Related: https://github.com/cloudfoundry/cf-release/issues/972

fail fast if no $CONFIG, and print sanitized $CONFIG

---

docker/docker_lifecycle_test.go

In the recent PR where I added these tests, I forgot to specify DEFAULT_TIMEOUT in the Eventually assertions. This caused tests to time out too quickly in the Diego CI environment.

Add DEFAULT_TIMEOUT to Eventually assertions in docker tests

---

v3/app_lifecycle_test.go
v3/package_test.go

Hello,
We are running CATs with a java buildpack that isn't named "java_buildpack", and noticed some v3 failures due to tests hardcoding that name. We've changed 2 instances of "java_buildpack" and 1 of "ruby_buildpack" being hardcoded to pull their values from the config JSON instead.
This will help anyone who is using a custom buildpack name vet their deployment using the v3 CATs.
Thanks,
Raina
PCF Release Engineering

Buildpack names are taken from config instead of hard-coded

---

v3/droplet_test.go

The original events query returned multiple pages but we weren't iterating over all the pages. If your event ended up on the second page the test would fail.
* An explanation of the use cases your change solves
Makes test less likely to fail by looking for the particular event the test specifies and the actee GUID. There should only be one event.
[#126327439]
Signed-off-by: Ryan Moran <rmoran@pivotal.io>

Make sure request only gets one event

---

assets/service_broker/setup_new_broker.rb

I often want to setup a broker on a domain besides bosh-lite.com, a1, or
tabasco.

Support an arbitrary domain besides the env_to_domain_mapping

---

helpers/config/config.go
helpers/config/config_struct.go
security_groups/running_security_groups.go

This updates the existing security-group tests in CATS for running applications to work with container networking.
It requires a new config option,`include_container_networking` which defaults to `false`
When false, the existing test is run using security groups.  When true, it instead uses the cf cli network policy plugin to create/remove policies.
To work with container networking, this will also require PR https://github.com/cloudfoundry/cf-acceptance-tests/pull/144 be merged.
- Initial work done here for context: [#132951677](https://www.pivotaltracker.com/story/show/132951677)
- Tracking story for this PR: [#133349151](https://www.pivotaltracker.com/story/show/133349151)
/cc @markstgodard

Update security groups test for compatibility with container networking

---

services/sso_lifecycle.go

Our api server is behind a proxy that redirects http to https, so making a request to the url without a protocol returns a 301 with an empty body, which panics the sso tests. This patch prepends the protocol to the api url--wdyt?

Include protocol in SSO URLs.

---

services/service_instance_lifecycle.go

This test recently broke because of a change in behavior to the "service-key" command - as a result of a bug fix in the CLI (tracker story #134271615).
In short, when running the "service-key" command, it used to exit 0 when the key is not found. It now exits 1. This PR updates a test assumption accordingly.

update "can delete the key" service test in service_instance_lifecycle.go

---

helpers/app_helpers/app_helpers.go

It makes the test output extremely verbose when running with the --succinct ginkgo flag. For example, when running just the v3 test group, the output currently looks like this:
```
+ ginkgo --failFast --succinct --nodes=4
[1482431888] CATS - 133/135 specs - 4 nodes 
------------------------------
App name was set to ""; skipping app report.
S
------------------------------
App name was set to ""; skipping app report.
SSSS
------------------------------
App name was set to ""; skipping app report.
S
------------------------------
App name was set to ""; skipping app report.
S
------------------------------
App name was set to ""; skipping app report.
S
------------------------------
App name was set to ""; skipping app report.
S
------------------------------
App name was set to ""; …
```

Remove empty app name message when running tests.

---

routing/zipkin_tracing.go

- this test has been extremely flakey due to
gbytes say not showing up in the requisite amount
of time.
- no reason to actually use an eventually as all of
the logs have already been fetched on the line above
and we are not waiting for them to "Eventually" come
in.
Signed-off-by: Zachary Gershman <zgershman@pivotal.io>

Remove Evenutally in favor of Expect

---

helpers/v3_helpers/v3.go

When the droplet upload for a package fails, the helper currently succeeds even though there is no GUID in the response. This fix checks for the existence of the GUID and fails fast when it's not there.
The same change could probably be made at many different places, but we weren't sure if that is appropriate and thus fixed only the one place were it hurt us so far.
/cc @suhlig

Fail fast when response does not include GUID

---

apps/loggregator.go

- CF CLI has deprecated this endpoint in the config
- Tests in loggregator.go were failing because they depend on the config.
Signed-off-by: Alex Melnik <aleksandr.s.melnik@hpe.com>

removed reference to loggregator endpoint in cf config

---

README.md

According to `cf-test-helpers`, long_curl_timeout, broker_start_timeout, and async_service_operation_timeout units are in minutes, not seconds.
https://github.com/alexjh/cf-acceptance-tests/blob/b17e0d76e5a708ec28e7152780a938d0d7cad49a/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/config/config.go#L195-L220

Fix units for test timeout documentation

---

helpers/app_helpers/app_usage_events.go
isolation_segments/isolation_segments.go
tasks/task.go
v3/app_lifecycle.go

- V3 helpers are still experimental, but tasks are not.
Backwards-incompatable Changes to the v3 helpers could break users
running the tasks suite.
Signed-off-by: Michael Xu <mxu@pivotal.io>

Remove v3 helpers from task suite

---

helpers/v3_helpers/app_usage_events.go

* When running v3 CATs on 25 nodes, we notice failures on finding the relevant App Usage Event on app START because it has been buried under many other app usage events. I've added the `results-per-page` to be consistent with https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/apps/lifecycle.go#L40 
[#141784943]

Update v3 test helper to request 150 app usage events per page

---

helpers/app_helpers/app_usage_events.go
tasks/task.go
v3/app_lifecycle.go

When querying for recent app usage events, follow pages so that we
won't miss an event due to high activity.
[#139323913](https://www.pivotaltracker.com/story/show/139323913)
Addresses issue #184 and pr #175
Signed-off-by: Aakash Shah <ashah@pivotal.io>

Improve assertions against app usage events

---

apps/loggregator.go
isolation_segments/isolation_segments.go

The CLI Team recently introduced a regression in the CATs tests. This PR updates the assertions such that they are backwards compatible with different cf cli versions.

Tests assertions are now compatible with different CF CLI versions

---

apps/syslog_drain.go

If the address is not yet in the log output, the test would have previously panicked on an "Index out of range" error.
This change ensures the address is present before continuing the test.

Fixes panic in apps/syslog_drain.go when address not yet in logs

---

cats_suite_test.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go

I'm proposing the following configuration flag to enable cleanup of persistent app org at the end of CATs runs for [this story](https://www.pivotaltracker.com/story/show/143441987).

[#143441987] Add configurable cleanup of persistent app org

---

apps/healthcheck.go
apps/routing_transparency.go
assets/golang/Godeps/Godeps.json
assets/golang/Procfile
assets/golang/manifest.yml
assets/multi-port-app/Godeps/Godeps.json
assets/multi-port-app/Procfile
assets/multi-port-app/manifest.yml
assets/syslog-drain-listener/manifest.yml
assets/worker-app/Godeps/Godeps.json
assets/worker-app/Procfile
assets/worker-app/manifest.yml
detect/buildpacks.go
route_services/route_services.go
routing/multiple_app_ports.go

- by using go native vendoring and not specifying GOVERSION, the go
buildpack will use the default version of Go. This should future-proof
these fixtures against versions of Go being removed from the buildpack
[#142416247]
Signed-off-by: Anna Thornton <athornton@pivotal.io>
Signed-off-by: Nikita Rathi <nrathi@pivotal.io>

Update go fixture apps to use default go version

---

README.md
docker/private_docker_lifecycle.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go

- Values for the image, username, and password must be provided
in the integration config to run these new tests.
[#144962927](https://www.pivotaltracker.com/story/show/144962927)
@jenspinney and @tcdowney

Add tests for apps and tasks based on private docker registries

---

bin/test

- current grep only removes password lines
- this grep still displays `include_private_docker_registry`
[#144962927]
Signed-off-by: Michael Xu <mxu@pivotal.io>

Redact private_docker_registry image and username

---

README.md
backend_compatibility/backend_compatibility.go
helpers/assets/assets.go

* add dora-droplet.tar.gz asset which has been staged on a DEA
* remove test checking compatibility between a droplet staged on
Diego -> DEAs
* do not use the binary asset, or a user specified start command: part
of checking compatibility is to ensure that a start command parsed by
staging on a DEA is usable on Diego
* update README.md
[#144070419]

backend compatibility test no longer requires DEAs

---

apps/default_environment_variables.go
assets/binary/app

This is for https://www.pivotaltracker.com/story/show/144961599. Note that the new specs require the next CAPI release to pass (current one is CAPI 1.28.0).

Add specs of environment variables during staging, running, and tasks

---

cats_suite_helpers/cats_suite_helpers.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/v3_helpers/v3.go
isolation_segments/isolation_segments.go

This commit includes a refactor to make the isolation segment-related functions public. Additionally, we fixed some test cleanup that had the side effect of leaving an isolation segment set as a default for an org.
This is in preparation for a future PR to implement a test suite for routing isolation segments.
Signed-off-by: Belinda Liu <bliu@pivotal.io>
Signed-off-by: Jonathan Berkhahn <jaberkha@us.ibm.com>

Refactor isolation segment test helpers

---

services/recursive_delete.go

Before, if the `cf delete-org` in the spec failed, then the afterEach
would fail to delete the quota.
Signed-off-by: Tim Downey <tdowney@pivotal.io>
```
cf delete-quota -f CATS-1-QUOTA-5baada7e-b579-45c2-7 
Deleting quota CATS-1-QUOTA-5baada7e-b579-45c2-7 as admin...
FAILED
Please delete the organization associations for your quota definition.
```

Fix ordering problem in afterEach

---

helpers/v3_helpers/v3.go

This fix is to correct the backward logic in CAT's helpers.
Signed-off-by: Belinda Liu <bliu@pivotal.io>

Fix logic in CreateOrGetIsolationSegment

---

apps/default_environment_variables.go
assets/binary/app

**WARNING**: Do not merge until `cf-deployment` master is using `capi-release` `1.29.0` or above.
Previously these tests would panic with the following message if log output from staging didn't match exactly what the tests expected:
```
Test Panicked
runtime error: index out of range
```
We've removed the need for it to look for `START_ENV_CMD` and `END_ENV_CMD` in the output so it should be a little more reliable and will output more meaningful failure messages.
- @ljfranklin && @tcdowney

Fix default environment variables #146531275

---

helpers/v3_helpers/v3.go
isolation_segments/isolation_segments.go
routing_isolation_segments/routing_isolation_segments.go

We don't have an environment that is setup to run the test at `routing_isolation_segments/routing_isolation_segments.go:103`, so we haven't been able to run this test, but we believe it's good.
[#145311439](https://www.pivotaltracker.com/story/show/145311439)
-- @anniesing && @mikexuu

Cleanup leaky isolation segment relationships

---

assets/service_broker/cats.json
helpers/services/broker.go
services/service_broker_lifecycle.go

This PR is a dupe of https://github.com/cloudfoundry/cf-acceptance-tests/pull/227 except it has been updated to reflect the later version of capi-release which includes [extra validation](https://github.com/cloudfoundry/cloud_controller_ng/pull/847).
We have run these branch on our bosh-lite.

Add Service Broker Schema tests take two

---

apps/encoding.go
detect/buildpacks.go

We are moving the Java buildback from v3 to v4. As a result, Java apps now require a higher minimum memory allotment.

Increase memory for Java apps 512M -> 1024M

---

assets/dora/README.md
assets/dora/dora.rb

The current `/env` endpoint returns a serialized Ruby hash. For this
response to be manipulated programmatically, it must be interpreted
back into a hash with a Ruby `eval`, which requires a Ruby interpreter
and is demonstrably insecure. A variant on this endpoint that returns
the environment as a JSON object is much safer and is language-agnostic.
There are no doubt some CATs that could improve the robustness of
their assertions by manipulating this JSON-formatted response.
No tests, but the Dora README is updated.

Add JSON-formatted environment endpoint to Dora

---

helpers/services/broker.go
services/service_broker_lifecycle.go

The Open Service Broker API is [proposing](https://github.com/openservicebrokerapi/servicebroker/issues/59) allowing brokers to define JSON schema for their configuration parameters.
[Create Instance Schema](https://github.com/cloudfoundry/cf-acceptance-tests/pull/229) CATs were previously added.
Support for [Update Service Instance Schema](https://github.com/cloudfoundry/cloud_controller_ng/pull/865) and [Create Binding Schema](https://github.com/cloudfoundry/cloud_controller_ng/pull/866) have now been added to the cloud_controller and have made their way to cf-release & cf-deployment.
This PR adds tests for update instance and create binding.
Feedback welcome!
Thanks,
Sam & @jenspinney

Add Update Instance / Create Binding Service Schemas

---

assets/credhub-enabled-app/README.md
assets/credhub-enabled-app/src/main/java/org/credhub/CredHubEnabledController.java
assets/credhub-service-broker/main.go
credhub/credhub_enabled.go

- Updates the Credhub Service Broker to take in a SERVICE_NAME
environment variable that allows it to have a CATS-specified name for
its service offering
- Also updates the Credhub Enabled App to look for this same env var to
properly read the service from its VCAP_SERVICES env
- Credhub Service Broker can now create CredHub credentials with both
mtls-app and uaa-client actors
[#150753759](https://www.pivotaltracker.com/story/show/150753759)

Add test for CredHub-enabled service keys

---

cats_suite_helpers/cats_suite_helpers.go

When running no tests this dropped the time from 45s to ~20s (bosh-lite)
Signed-off-by: Vikram Yadav <vyadav@pivotal.io>

Wrap the callback in a describe in order to avoid AfterEach invocations

---

cats_suite_helpers/cats_suite_helpers.go
credhub/credhub_enabled.go
docker/credhub_enabled.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go

also updated the docker credhub test to use the new flag and added a
non-assisted test to assert VCAP_SERVICES are not automatically interpolated in
that mode
[#151926448]

add a flag to differentiate between assisted and non-assisted modes

---

tasks/task.go

- Smaller environments might be too slow to catch the running state

Allow task to be running or succeeded

---

helpers/config/config.go
helpers/config/config_struct.go
security_groups/running_security_groups.go

Added a new parameter to configure unallocated IP for security group test, default is `10.0.244.255`
Signed-off-by: Josh Zarrabi <jzarrabi@pivotal.io>

Make random IP configurable in security group test

---

apps/admin_buildpack_lifecycle.go
apps/app_stack.go
apps/buildpack_cache.go

* netcat closes connections immediately by default, which causes
envoy TLS connections to hang.
[#149828242]
Signed-off-by: Nima Kaviani <nkavian@us.ibm.com>

Wait 1 second for selected netcat-based tests to close connections.

---

services/service_broker_lifecycle.go

This is no longer required as per v2.13 of the Open Service Broker Api Specification. Updating CATs to reflect the loosening of this requirement.
[#150877576](https://www.pivotaltracker.com/n/projects/2105761/stories/150877576)
Thanks,
Sapi (ablease, @jenspinney)

Remove type from service schemas

---

apps/lifecycle.go
services/service_instance_lifecycle.go

- made tests more flexible towards casing and spacing
- assert on combined stdout and stderr output
- tests are backwards compatible to pre service refactor

make service instance tests compatible with refactored CLI service command

---

README.md
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
services/service_instance_sharing.go

This PR adds initial tests of the new service instance sharing feature. The new feature allows users who have the `service_instance_sharing` feature flag enabled to share a service instance with spaces other than the orginitating space of the instance.
Because this feature only works if the feature flag is on, we needed to add a new config option to the integration config. We called this `include_service_instance_sharing`. The test file itself is part of the services suite, so the tests will only run if both `include_service_instance_sharing` and `include_services` are true.
These tests pass on the lastest version of cf-release (v280), the latest version of capi-release (1.45.0), and the master branch of cf-deployment (which uses capi-release 1.45.0).

Test service instance sharing

---

assets/service_broker/cats.json
assets/service_broker/data.json

Newer cloud_controller versions (not yet included in a capi-release referenced in cf-release/cf-deployment) include checks that brokers have a sharable metadata property in order to be shared.
This change allows the service instance sharing CAT tests to be forward compatible with the latest version of capi.
Thanks,
Sam

Add config to make services shareable

---

helpers/download/download.go

When Cloud Controller is backed by an NFS blobstore its download endpoints don't return a redirect url, but instead send the file directly to the client. This meant that CATS using this helper would fail when run against an NFS-backed environment.
[#153418205](https://www.pivotaltracker.com/story/show/153418205)
Thanks!
Tim and @ericpromislow

Update download helper to handle immediate downloads

---

helpers/download/download.go

This commit makes the regexp on the curl request case insensitive when it's looking for redirect locations. This was affecting certain curl commands depending on the infrastructure.

make regexp case insensitive

---

README.md
helpers/config/config_struct.go
helpers/config/config_test.go

* Includes README updates as well since `cc.diego.temporary_local_apps` will be `true` by default in `capi-release` `1.46.0`.
Tracker story: [#152623585](https://www.pivotaltracker.com/story/show/152623585)
Thanks!
Tim && @ericpromislow

Runs IncludeCapiNoBridge tests by default

---

docker/private_docker_lifecycle.go

The error message will differ depending on your diego version and whether you have grootfs enabled.
grootfs error message
```
Failed to talk to docker registry: Get https://192.168.50.1:5000/v2/: http: server gave HTTP response to HTTPS client
Failed getting docker image by tag: unauthorized: authentication required  Going to retry attempt: 1
Failed getting docker image by tag: unauthorized: authentication required  Going to retry attempt: 2
Failed getting docker image by tag: unauthorized: authentication required  Going to retry attempt: 3
Failed getting docker image by tag: unauthorized: authentication required
Staging process failed: Exit trace for group:
builder exited with error: failed to fetch metadata from [diego-docker-app-custom] with tag [latest] and insecure registries …
```

Update the private docker registry invalid credentials expectation

---

cats_suite_test.go
services/service_instance_sharing.go

Since the [latest CLI version](https://github.com/cloudfoundry/cli/releases/tag/v6.34.0) contains the new `v3-share-service` and `v3-unshare-service` commands, we can replace the `cf curl` calls in the service instance sharing tests for better end-to-end coverage.
We've also removed some assertions about the additional sharing data returned by `cf service` because they are now covered in the CLI's [integration tests](https://github.com/cloudfoundry/cli/blob/master/integration/isolated/service_command_test.go).

Use CLI for share and unshare

---

apps/large_payload.go

I can no longer see the referenced story, but from 34d1c48 it looks like the
original intention of this test was highlight problems delivering large
responses from CF applications caused by MTU misconfiguration.
We recently experienced a problem like this which has been described in
cloudfoundry/guardian#77. This test passed because the response size of 5kB
was smaller than the MTU size of 9kB on some AWS instance types:
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html#jumbo_frame_instances
Increasing this to a larger value will make the test more effective. I've
chosen a value of 200kB because it's larger than standard MTUs and
indicative of the response from an average website.

Increase large payload test from 5kB to 200kB

---

assets/proxy/Procfile
assets/proxy/README.md
assets/proxy/handlers/download_handler.go
assets/proxy/handlers/download_handler_test.go
assets/proxy/handlers/handlers_suite_test.go
assets/proxy/handlers/info_handler.go
assets/proxy/handlers/ping_handler.go
assets/proxy/handlers/proxy_handler.go
assets/proxy/handlers/stats_handler.go
assets/proxy/handlers/stats_handler_test.go
assets/proxy/handlers/upload_handler.go
assets/proxy/handlers/upload_handler_test.go
assets/proxy/integration/integration_suite_test.go
assets/proxy/integration/integration_test.go
assets/proxy/main.go
assets/proxy/manifest.yml
helpers/assets/assets.go
service_discovery/service_discovery.go

Use proxy app in service_discovery tests. 
There is an issue with using cf ssh with a curl command in cats. See open issue here: https://github.com/cloudfoundry/cf-acceptance-tests/issues/266
To mitigate this, we added our proxy app and are curling that instead.
[#155208790]
Signed-off-by: Aidan Obley <aobley@pivotal.io>

make service_discovery test use proxy app

---

apps/default_environment_variables.go

Currently the code uses the output from the cf start command.
it is definitely possible that the CLI may be slow connecting to doppler and thus misses these messages.
This causes a failure when it really should be a success as for this test the purpose is to test the variables are set not that you can see them on the cf cli start command.
This change therefore will use cf logs to retrieve the logs from the start and will correctly check if the variables are set.

Change to check the variables with cf logs

---

.gitignore
README.md
apps/default_environment_variables.go
apps/environment_variables_group.go
apps/healthcheck.go
apps/loggregator.go
apps/syslog_drain.go
helpers/app_helpers/app_helpers.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/logs/logs_helper.go
route_services/route_services.go
routing/zipkin_tracing.go
security_groups/running_security_groups.go
ssh/ssh.go

This PR adds the ability to use the new [log-cache](https://github.com/cloudfoundry/log-cache) and `log-cache-cli` for getting application logs.
Using log-cache is disabled by default and can be enabled via the CATs JSON config.

Optionally use log-cache for logs

---

assets/service_broker/cats.json
assets/service_broker/data.json
assets/service_broker/service_broker.rb
services/service_instance_lifecycle.go

This PR adds tests of the new fetching broker parameters feature. It allows users who have the created a service instance, service binding, service key or route-service with parameters, the `-c` option on the CF CLI, to retrieve those parameters if the broker allows it.
These tests pass on cf-deployment (v1.24.0) which contains the latest version of capi-release (1.53.0)

Add CATs for fetching broker parameters feature

---

windows/metrics.go

The existing Windows metrics test tested that there were metrics emitted to loggregator that had the origin "garden-windows". This change removes this test as it is not a real "acceptance test" for CF and also becomes incompatible once windows2012R2 cells disable UDP on the metron agent. We have matched the `apps/loggregator` metrics tests in order to get parity between the stacks.
**Note:** We have not yet made an effort to remove test duplication as we are leaving that up to the relint team to decide on. If you think we should start to think about reducing duplication as part of this PR, we can definitely do so.

Windows metrics test matches linux test

---

assets/dora/dora.rb

- Implementation used to rely on `man` being installed
- It is not installed on default CF buildpack
- Alternative implementation uses Ruby `Signal.list`
Pair with @blgm

Fix `GET /sigterm` endpoint for Dora

---

windows/context_paths.go

.NET Apps must be pushed with --no-start --no-route before cf map-route
in order to use context paths.

fix windows context path tests

---

helpers/config/config_struct.go
helpers/config/config_test.go

It was documented as `use_windows_context_path`, but the config struct
was actually parsing `windows_context_path`. So anyone with
`use_windows_context_path` set in their config was silently and
unexpectedly skipping this test
Signed-off-by: Amin Jamali <ajamali@pivotal.io>

Fix `use_windows_context_path` config

---

tasks/task.go

Platforms serving apps via HTTPS may use a redirect to promote from
HTTP. For such platforms using `curl` without `-L` produces an empty
response and consequent test failure.

Allow HTTP redirect in task overlay network tests

---

README.md
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
windows/wcf.go

We were testing that multiple WCF apps could be colocated on the same
cell. This is a better fit for our Windows regression tests:
https://github.com/cloudfoundry/windows-regression-tests
So we now will only push one instance and test that it works.
This should remove any flakiness caused by this test.

Change multi-instance WCF test to single-instance

---

apps/loggregator.go

If running with tail, header will not be emitted
- CATs will never run as a terminal
[#157710932]
Signed-off-by: Todd Persen <tpersen@pivotal.io>
/cc @toddboom

cf tail doesn't expect header

---

assets/service_broker/cats.json
assets/service_broker/service_broker.rb
helpers/services/broker.go
services/service_instance_lifecycle.go

This PR adds tests for the new asynchronous binding create feature. It allows users to create bindings asynchronously by providing `accepts_incomplete` flag. The flow is very similar to asynchronous service instance provisioning.
List of the changes:
* add new async bind response behavior to the fake broker
* add new last_operation endpoint for the binding to the fake broker
* add async binding create test
* minor refactoring
These tests pass on cf-deployment (v1.37.0) with capi-release (1.59.0)

Add CATs for asynchronous binding create feature

---

capi_experimental/manifest.go

Change the regex to be backwards/forwards compatible with changes coming in from [#158450180](https://www.pivotaltracker.com/story/show/158450180).
Passing against an edge binary and what's current stable (6.37.0).

compatible way to check service binding

---

apps/admin_buildpack_lifecycle.go

We updated the app command to display `buildpacks` instead of `buildpack` as part of the multiple buildpacks feature. This is a backwards compatible change with previous CLIs.
[#158607105]

assert on both buildpack and buildpacks

---

service_discovery/service_discovery.go

We run a proxy in front of the gorouter that redirects http to https, so this test fails without adding the protocol to the url.

Add protocol to service discovery app url.

---

README.md
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
service_discovery/service_discovery.go

Hi RelInt, 
Container Networking no longer assumes that the internal domain `apps.internal` is present and instead requires the user to configure their own internal domain. This PR reflects those changes.
<hr>
- for service discovery
- no longer assume that apps.internal is present, since it is no longer
seeded by capi or hardcoded in the bosh dns adapter
- users must now BYO internal domain
[#158296930]
Signed-off-by: Amelia Downs <adowns@pivotal.io>

add internal domain as a config param

---

helpers/config/config_struct.go

Signed-off-by: Jesse Weaver <jeweaver@pivotal.io>
Yes, thank you for asking.
Since Log Cache is now GA in cf-d, this turns on testing of Log Cache by default.
Talked to @staylor14 about flipping this default on 8/22. This seems to make sense to all parties involved since Log Cache is now GA in cf-d.
This was run against cf-d 3.4.0 in our own pipeline.
N/A
Testing log tailing with Log Cache is now enabled by default.
This should speed up CATs since tailing previously used to be somewhat slow.
/cc @pianohacker @colins @hdub2

Enable fetching of logs through log-cache by default

---

assets/service_broker/cats.json
services/service_instance_lifecycle.go

Asynchronous Binding Delete operation has been added to Cloud Controller, as part of the CF Deployment Release v3.2, CAPI Release 1.65. We are adding tests to CATS to assert on the flow of that feature.
List of the changes:
Asynchronous Binding Delete flow
@cloudfoundry/services-api

Async binding delete

---

helpers/v3_helpers/v3.go

Our CI pipelines would occasionally fail with:
```
[2018-08-23 04:32:10.48 (UTC)]> cf curl /v3/isolation_segments -X POST -d {"name":"isosegtag"}
{
"errors": [
{
"detail": "Isolation Segment names are case insensitive and must be unique",
"title": "CF-UnprocessableEntity",
"code": 10008
}
]
}
```
We think this is due to running this suite in parallel and the Find or
Create pattern is causing this race condition. We switch to always
attempting to create the Iso Seg first, then calling Find only if the
Create fails. This assumes the Create failed due to the unique
constraint shown above.
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io> …

Avoid race condition when creating iso seg

---

security_groups/running_security_groups.go

This commit enables CF foundations using the NSX-T container plugin (NCP) to pass the security groups test. NCP's mechanism to deny egress is to drop packets, resulting in timeouts, whereas Silk refuses packets. The test now accommodates `Connection timed out` failures as well as `connection refused`.
See https://github.com/cloudfoundry/cf-networking-release/pull/49 for a similar change made to the networking acceptance test suite.
This has been run against PAS 2.2.4 and 2.3.0-beta.2.
This commit enables CF foundations using the NSX-T container plugin (NCP) to pass the security groups test. [NCP's mechanism to deny egress is to drop packets, resulting in timeouts, while Silk's is to refuse packets (i.e., to send a TCP reset)]. The test now accommodates `Connection timed out` (`ETIMEDOUT`) …

Allow security groups to pass on NSX-T

---

assets/python/Procfile
assets/python/runtime.txt
assets/python/server.py

The python fixture app was single threaded and could only service one request/connection at a time. This change enables the python fixture app to now accept multiple concurrent connections.
The app being single-threaded was a problem in diego environments with route integrity enabled that deployed the latest version of the Envoy proxy. Envoy now uses tcp connection pooling and during CATs the python app in question would fail to respond to requests as a result of being blocked on open connections in the Envoy pool. The app would also fail to start when pushed with the `http` healthcheck for similar reasons. Route integrity/Envoy is not the only situation that could cause this, this would also happen if connection keepalives were turned on from gorouter.
We are also digging in with the …

Modify python fixture app to be multithreaded

---

apps/syslog_drain.go
assets/syslog-drain-listener/syslog_drain.go

NSX-T networking communicates over the internal (container overlay network), unlike the stock PAS deployment, which requires the use of the external network (i.e. the network where the diego cells attach). This test now accommodates both by creating syslog drains on both networks, one of which will work on NSX-T and one on vanilla deployments.
To this end, the syslog drain app deployed by the test also reports both its external and internal addresses.
See earlier changes for NSX-T, #333 and #331, which address another difference between NSX-T and vanilla networking.
PAS 2.3.0
Allow syslog drain test to pass on NSX-T
This should not significantly change runtime.
cc @rowanjacobs @goehmen @rosenhouse

Allow syslog drain test to pass on NSX-T

---

security_groups/running_security_groups.go

This commit enables CF foundations using the NSX-T container plugin (NCP) to pass the security groups test when connecting with non-existent host. NSX-T's mechanism is to send an ICMP Host Unreachable (`No route to host`), which we attempted to accommodate with a previous PR; however, given catnip's short `curl` timeout, the connection frequently times out before the ICMP packet is received, causing spurious failures. The test now accommodates `Connection timed out`, `no route to host`, and `connection refused`.
See #331 for our first attempt to fix this.
PAS 2.3.0.
Allow security groups test to pass on NSX-T, accommodating both `No route to host` and `Connection timed out` errors.
This change will not affect the runtime of CATS.
cc @rowanjacobs @goehmen

Allow ASG tests to pass on NSX-T

---

README.md
cats_suite_helpers/cats_suite_helpers.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go
internetless/app_dns_resolution.go
internetless/app_external_traffic_denied.go

Adding a test suite that verifies a deployment does not allow external traffic from app containers.
Slack: https://pivotal.slack.com/archives/C3LUD2L04/p1538515665000100
Story: https://www.pivotaltracker.com/story/show/160211045
Not cf-deployment...
Technically, there is a new config option for the new test, so if the user wants to run that test, they would need to update their CATs integration-config but otherwise, it defaults to false.
See slack conversation.
Adds a test that verifies a deployment does not allow external traffic from app containers.
0s if not enabled.
@acrmp @mcwumbly

Add internetless test suite

---

ssh/ssh.go

Seeing the following failure periodically on GCP:
```
• Failure [17.473 seconds]
[ssh] SSH ssh [It] runs an interactive session when no command is provided
/tmp/build/33ac16d1/go/src/github.com/cloudfoundry/cf-acceptance-tests/ssh/ssh.go:93
Expected error:
<*exec.ExitError | 0xc4204c0120>: {
ProcessState: {
pid: 28056,
status: 256,
rusage: {
Utime: {Sec: 0, Usec: 190025},
Stime: {Sec: 0, Usec: 57833},
Maxrss: 25804,
Ixrss: 0,
Idrss: 0,
Isrss: 0,
Minflt: 3099,
Majflt: 0,
Nswap: 0,
Inblock: 0,
Oublock: 200,
Msgsnd: 0,
Msgrcv: 0,
Nsignals: 0,
Nvcsw: 2803,
Nivcsw: 28,
},
},
Stderr: nil,
}
exit status 1
not to have occurred
/tmp/build/33ac16d1/go/src/github.com/cloudfoundry/cf-acceptance-tests/ssh/ssh.go:115
```
This PR tries to add more logging to help diagnose the underlying issue
_All PR's …

Add more verbose logging around SSH test

---

README.md
helpers/config/config_struct.go
helpers/config/config_test.go
windows/running_security_groups_win.go

[#161817037]
Yes
Add support for `-s windows` in CATS
https://www.pivotaltracker.com/story/show/161817037
release-candidate
No new test
Add windows stack `-s windows` for CATs
N/A

Add windows stack support

---

helpers/app_helpers/app_helpers.go
v3/service_instances.go

Following on from discussion in Slack (https://cloudfoundry.slack.com/archives/C5WH3RDLZ/p1547590986036300) this PR moves the service instance tests from experimental to v3.
We also noticed that the test was not cleaning up after itself, so we added that.
@henryaj

Move service instance test from exp. to v3

---

helpers/download/download.go
helpers/download/download_suite_test.go
helpers/download/download_test.go

yes
'can copy package bits to another app and download the package' in `v3/package.go` fails with a confusing unzip error, when api redirects multiple times, because it tries to unzip the body of a redirect. This change stops on the second redirect with an error message emulating what the cf CLI would do.
I've started a [conversation on the cf CLI Slack](https://cloudfoundry.slack.com/archives/C032824SM/p1548426413059900) and it seems like it is not on purpose that the CLI doesn't follow more than 1 redirect. Once it's changed in the cf CLI, it would be preferable in the code that I've refactored here, to actually just follow all redirects just as the CLI does to be in parity. Then the improved error reporting introduced here might not be needed anymore, unless of course you decided to …

Improve error reporting when API redirects multiple times

---

helpers/download/download.go
helpers/download/download_suite_test.go
helpers/download/download_test.go

This is exactly the same as https://github.com/cloudfoundry/cf-acceptance-tests/pull/354, but correctly handling HTTP/2 (including additional tests), for which the previous one was reverted in https://github.com/cloudfoundry/cf-acceptance-tests/commit/1200e986bed44040c253eb2fb6c7b4bb10133cd4.
For your convenience, the text from the original PR:
yes
'can copy package bits to another app and download the package' in `v3/package.go` fails with a confusing unzip error, when api redirects multiple times, because it tries to unzip the body of a redirect. This change stops on the second redirect with an error message emulating what the cf CLI would do.
I've started a [conversation on the cf CLI Slack](https://cloudfoundry.slack.com/archives/C032824SM/p1548426413059900) and it seems like it is …

Allow 10 redirects in download.WithRedirect, this time also working with HTTP/2

---

helpers/download/download.go
helpers/download/download_suite_test.go
helpers/download/download_test.go

This is exactly the same as https://github.com/cloudfoundry/cf-acceptance-tests/pull/357, but correctly handles an HTTP line that has no textual status code (including additional tests), for which the previous one was reverted in https://github.com/cloudfoundry/cf-acceptance-tests/commit/ee32761a2ae469d4f526eb4766a1997b60f74a8d.
For your convenience, the text from the original PR:
yes
'can copy package bits to another app and download the package' in `v3/package.go` fails with a confusing unzip error, when api redirects multiple times, because it tries to unzip the body of a redirect. This change stops on the second redirect with an error message emulating what the cf CLI would do.
I've started a [conversation on the cf CLI Slack](https://cloudfoundry.slack.com/archives/C032824SM/p15484264 …

Introduce curl download redirects (3rd attempt)

---

cats_suite_test.go

* The original code breaks with go 1.12 which requires HOME to be set.
This method is more future-proof, if later versions of Go require
other env vars.
Signed-off-by: Seth Boyles <sboyles@pivotal.io>
Done
Go 1.12 now requires the gocache. With the old code, the call to `go build -o bin/catnip`
failed with the error message `build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined`
The cause of the error is straightforward and somewhat generic: it's better to append to
the existing environment than to try to respecify a complete environment for the subprocess.
7.5.0
none of the above
n/a
not needed
should be negligible
urgent for any teams moving to go 1.12
@ericpromislow @sethboyles @cloudfoundry/cf-capi  PM @ssisil

Better to add to the existing environment than specify it completely.

---

apps/syslog_drain.go

[#164224800]
Signed-off-by: Tom Chen <tochen@pivotal.io>
Yes
We added tests for the V3 of syslog drain
https://www.pivotaltracker.com/story/show/164224800
v7.6.0
This functionality is only complete in the context of a cf deployment. Also, there was already a test in CATS for the V2 syslog drain.
Test added to verify syslog drains V3
The test should add at most 30s
@jtuchscherer, @chentom88

Add syslog v3 drain tests

---

apps/default_environment_variables.go

Signed-off-by: Akshay Mankar <amankar@pivotal.io>
Yes
When tasks are disabled in the config, the environment variable test still runs the task 
SCF + Eirini
* FIX: Stop running tasks in the environment variable test when tasks are disabled
up to 1 minute less when tasks are disabled
With 💚 from @cloudfoundry/eirini

Check env variables in tasks when they are enabled

---

example-cats-config.json

It doesn't appear to be a real thing.

Remove `include_assisted_credhub` from ex. config

---

helpers/logs/logs_helper.go

Yes
This removes the application metric envelopes that often pollute the generic `cf tail` output and make test failure output harder to read.
Use `cf tail` `--envelope-class` flag to reduce test failure output pollution by metric envelopes

Use cf tail --envelope-class flag to only get logs in logs helper

---

apps/lifecycle.go

Co-authored-by: Connor Braa <cbraa@pivotal.io>
Co-authored-by: Renee Chu <rchu@pivotal.io>
sometimes the test app here uses an amount of memory measured in K, not M or G. This causes the test to fail erroneously.
fix container metrics regex to accomodate apps with less memory
@reneighbor @cdutra

fix container metrics regex to accomodate apps with less memory

---

README.md
cats_suite_helpers/cats_suite_helpers.go
windows/asp_classic.go
windows/context_paths.go
windows/credhub_assist.go
windows/dynamic_info.go
windows/http_healthcheck.go
windows/instance_reporting.go
windows/lifecycle.go
windows/metrics.go
windows/output_volume.go
windows/routing.go
windows/running_log.go
windows/running_security_groups_win.go
windows/set_start_command.go
windows/ssh.go
windows/standalone_webapp.go
windows/tasks.go
windows/wcf.go

This change bumps the `DEFAULT_MEMORY_LIMIT` for .NET apps from 256MB to 1GB. 
While 256MB is enough for most cases, it seems to be just at the edge causing some tests to flake for .NET apps.
We noticed some of the Windows CATS were flaking [in our pipelines](https://garden-windows.ci.cf-app.com/teams/main/pipelines/winc/jobs/pesto-cats-2019/builds/247) as well as Rel-Eng's.
Upon inverstigation we discovered that raising the memory limit for the app caused the flakiness to disapear.
See [#165228529](https://www.pivotaltracker.com/story/show/165228529) for the details of our investigation, and [this slack thread](https://pivotal.slack.com/archives/CER7X0FFE/p1553092526119200) for our discussion with Rel-Eng about this issue.
`v7.11.0`
N/A
Add a DEFAULT_WINDOWS_MEMORY_LIMIT
- .NET apps …

Raise windows default memory

---

apps/loggregator.go

Signed-off-by: Travis Patterson <tpatterson@pivotal.io>
If RLP does not respond with any logs, this test hangs forever rather than failing.
https://cloudfoundry.slack.com/archives/C02HCCXV5/p1560355613038500
https://www.pivotaltracker.com/story/show/166645909
v9.3.0
Fix an issue where RLP tests might hang.
Potentially many fewer seconds in the failure case. The same amount of time in the success case
@MasslessParticle @AllenDuet

avoid hanging in RLP test by adding timeout

---

assets/multi-port-app/build-and-push-windows.sh

cc @sophiewigmore 
The multi-port app should be built for windows and pushed to the windows stack. Additionally, users will need to configure the app with the cf cli to open up the new ports it's running on.
This is related to supporting route integrity & tls on windows by using nginx in place of envoy. https://www.pivotaltracker.com/story/show/165793495
Does not acceptance the test itself.

Add script to build and push multi app.

---

apps/lifecycle.go
helpers/app_helpers/app_helpers.go
windows/lifecycle.go

Yes
Adds a test for `cf restart-app-instance`. The test is the same as in the windows tests.
[Link to story in Eirini tracker](https://www.pivotaltracker.com/story/show/164894822)
Test were ran against [SCF v2.15.2.1](https://github.com/SUSE/scf/tree/2.15.2.1)
This test is already present in the windows suite and should also be a part of the default apps tests.
Add test to verify `cf restart-app-instance`. Extract functions for gathering instance ids to `app_helpers`
Our tests ran between 60-80s.
@cloudfoundry/eirini

Add restart-app-instance test to app lifecycle

---

v3/service_instances.go

👍🏻
If you run CATS with multiple nodes, services will be created by other tests which collide with the v3/service_instances.go test which expects to only find the services that the test has created. The solution is to add a parameter to the v3 API call which filters services by space.
See #359 
This has been tested against cf-deployment v9.2.0
N/A
Fixes an issue where the v3 service instances tests would occasionally fail due to a race condition
< 1 second
N/A

Fix for #359 where tests flake with multiple nodes

---

README.md
helpers/config/config_struct.go
helpers/config/config_test.go
windows/running_security_groups_win.go

The legacy "windows2016" stack is deprecated and not supported
anymore by CF that uses windows cells.
Use of apps with "windows2016" stack is no more part of
the acceptance criteria for windows.
See https://docs.cloudfoundry.org/devguide/deploy-apps/windows-stacks.html
> The windows2016 stack is not supported on Cloud Foundry.
Removed the `windows2016` stack.

Remove windows2016 stack

---

README.md
helpers/config/config.go
helpers/config/config_struct.go
volume_services/volume_services.go

[#167932835](https://www.pivotaltracker.com/story/show/167932835)
> Yes
> Having the ability to run volume-services suite without any external nfs server running. Instead the suite 'creates' a nfs server to run tests against.
> We would like it to be easier to run the volume services suite
> https://github.com/cloudfoundry/cf-deployment/commits/29bd9ac01754398587623435403437da894f6684
- [ X ] changes an existing test
- [ X ] requires an update to a CATs integration-config
> We removed an unused configuration property `volume_service_create_config`
- [ X ] YES
n/a
Volume services test now uses a cf-pushed "in-memory" nfs server
~1 minute
- [ X ] **Urgent** - unblocks current or future work
cc/ @DennisDenuto @julian-hj

Volume services test uses a cf-pushed nfs server

---

bin/test

Yes
As all of the dependencies are vendored, we should leverage that. This saves about a minute in our (Eirini team's) CI.
N/A
SCF + Eirini
N/A
cf-acceptance-tests will leverage vendored modules using `-mod=vendor`. This means go versions less than 1.11 will not be supported.
This change cuts down 55 seconds.
@alex-slynko

Run tests faster with mod=vendor

---

README.md
helpers/config/config.go
helpers/config/config_struct.go
volume_services/volume_services.go

Allow volume service create config to be specified so that we can support testing against external volume services such as SMB
[#167082052](https://www.pivotaltracker.com/story/show/167082052)
v12 release candidate
n/a
Allow volume service create config to be specified to support testing against external volume services such as SMB
n/a
cc /@julian-hj @DennisDenuto

Allow volume service create config to be specified

---

README.md

See also https://github.com/cloudfoundry/cf-acceptance-tests/pull/386
Yes
https://github.com/cloudfoundry/cf-acceptance-tests/pull/386 introduces a flag that has been added in Go 1.11. Also, it most probably won't work in GOPATH
https://github.com/cloudfoundry/cf-acceptance-tests/pull/386
N/A
Should have done it in previous PR :(
N/A
cf-acceptance-tests should run outside of GOPATH
N/A

`bin/test` requires Go 1.11

---

volume_services/volume_services.go

The volume services test suite is a little flakey.
This commit randomizes the shared domain that the volume services test creates and increases the timeout for starting the nfs server.
Also removes unnecessary cleanup of apps/tasks in the random org (since it is recursively deleted).
#169354687
##What version of cf-deployment have you run this cf-acceptance-test change against?
Release candidate
introduces a new test --- Are you sure everyone should be running this test?
changes an existing test
requires an update to a CATs integration-config
Did you update the README as appropriate for this change?
YES
N/A
##How should this change be described in cf-acceptance-tests release notes?
Improve the repeatability of the volume services test in CATs by adding the correct timeouts and randomizing …

cleanup + improve volume service tests against flakes

---

volume_services/volume_services.go

The volume services test suite is a little flakey. I attempted to randomize the tcpDomain in the last PR (see below) but this caused other issues (app would flakily fail to start sometimes but not clear why).
Propose reverting randomizing the  part to timebox this chore
https://github.com/cloudfoundry/cf-acceptance-tests/pull/391
#169354687
##What version of cf-deployment have you run this cf-acceptance-test change against?
Release candidate
introduces a new test --- Are you sure everyone should be running this test?
changes an existing test
requires an update to a CATs integration-config
Did you update the README as appropriate for this change?
YES
N/A
##How should this change be described in cf-acceptance-tests release notes?
Improve the repeatability of the volume services test in CATs …

Revert "Randomize the shared domain created by this spec"

---

example-cats-config.json

The example config has a duplicated entry, which can make the behaviour of the suite very confusing if they have different values!

Remove duplicate entry from example config

---

assets/python/runtime.txt
assets/python/server.py

Updates the python app asset to use Python 3.x. Newer versions of the python-buildpack do not support Python 2.x anymore.
See reported issue: https://github.com/cloudfoundry/cf-acceptance-tests/issues/407
The python app asset has been updated to use Python 3.
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

Update python app to Python 3.x

---

assets/nora/README.md

Looks like ./make_a_nora no longer exists, and this simple command to "cf
push" nora works.
We had trouble deploying nora. This should help others avoid that trouble.
@christianang @KauzClay

Add `cf push` command to nora README

---

README.md
cats_suite_helpers/cats_suite_helpers.go
helpers/skip_messages/skip_messages.go
volume_services/volume_services.go

- and disable again afterwards
Co-authored-by: Paul Warren <pwarren@pivotal.io>
Co-authored-by: Lisa Burns <lcho@pivotal.io>
We are paying down some tech debt.  we wanted both pats and cats to work the same way; i.e. be responsible for enabling docker, rather than having the responsibility in the test one place and in the pipeline in another.
[#172250234](https://www.pivotaltracker.com/story/show/172250234)
a smith claimed cf-deployment
n/a
negligible.  all the test does is run two extra cf commands to enable the docker feature flag
@cloudfoundry/cf-volume-services

Enable docker before tests

---

README.md
apps/admin_buildpack_lifecycle.go
apps/app_stack.go
apps/app_staging_environment.go
apps/buildpack_cache.go
apps/default_environment_variables.go
apps/environment_variables_group.go
cats_suite_helpers/cats_suite_helpers.go
credhub/service_bindings.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go
security_groups/running_security_groups.go
v3/buildpacks.go

Add the ability to control which tests will run based on the configured infrastructure ("kubernetes" or "vms")
https://www.pivotaltracker.com/story/show/174026222
v13.11.0
Adds the ability to control which tests will run based on the configured infrastructure ("kubernetes" or "vms")
Skipping tests should make CATs run faster.
@cloudfoundry/cf-release-integration

Skip tests on k8s

---

apps/wildcard_routes.go
credhub/service_bindings.go
credhub/service_keys.go
docker/credhub_enabled.go
windows/credhub_assist.go

Update tests to always target the test space to cause tests to explicitly fail if there are either no spaces in an org, or multiple spaces.
https://www.pivotaltracker.com/story/show/174075058
v13.11.0
Update tests to always target the test space to cause tests to explicitly fail if there are either no spaces in an org, or multiple spaces.
N/A
cc @paulcwarren

Always target the test space

---

apps/admin_buildpack_lifecycle.go

yes
- The CLI output for `cf app` is changing in v7. The buildpacks output will be in table format. This breaks a couple CATS.
- This change makes the tests compatible with the new output as well as the old output.
https://www.pivotaltracker.com/story/show/173716617
master
NA
NA
shouldn't affect runtime
@cf-cli-eng

Make test compatible with CLI output format

---

apps/changing_start_command.go
apps/droplet_uploading_and_downloading.go
apps/environment_variables_group.go
apps/lifecycle.go
assets/catnip/manifest.yml
docker/private_docker_lifecycle.go
helpers/app_helpers/app_droplet.go
helpers/app_helpers/app_usage_events.go
helpers/services/broker.go
helpers/v3_helpers/destination.go
helpers/v3_helpers/v3.go
routing/multiple_app_ports.go
security_groups/running_security_groups.go
ssh/ssh.go
tasks/task.go
v3/app_lifecycle.go
v3/deployment.go
v3/droplet.go
vendor/github.com/cloudfoundry-incubator/cf-test-helpers/workflowhelpers/internal/space.go
volume_services/volume_services.go
windows/lifecycle.go
windows/running_security_groups_win.go
windows/ssh.go
windows/worker.go

Yes
These commits convert calls leveraging v2 Cloud Controller API endpoints to use the v3 CAPI endpoints, as part of VAT's work to deprecate v2 CAPI.
- Original PR: https://github.com/cloudfoundry/cf-acceptance-tests/pull/435
- Slack conversation regarding making these changes and PR-ing them in as a collective: https://pivotal.slack.com/archives/C3LUD2L04/p1595277418062500
- VAT Tracker epic for these conversions: https://www.pivotaltracker.com/epic/show/4611384
v13.19.0
N/A
Migrate endpoints leveraging v2 Cloud Controller API endpoints to v3.
It should be minimal, however we are aware that some endpoints seem to be slower in v3. We are working on making improvements to performance, and if any tests seem to run really slowly we would love to hear that feedback from you all!
@tstannard …

Migrate CATs to use only v3 CAPI endpoints

---

apps/routing_transparency.go
helpers/skip_messages/skip_messages.go

Ya 👍 
Istio performs some URL normalization so it does not have _complete_ route transparency like the Gorouters do. For various reasons this is desired behavior on the Istio side and they will not be changing it. We think that based on the history of this CAT (https://github.com/cloudfoundry/gorouter/issues/46) that this behavior is fine to differ between Gorouter and Istio-Proxy.
This change does the following:
- adds a new config property, `UseKubernetesIstioProxy` to use as a flag
for asserting on behavior differences between Gorouter and Istio Proxy. This property defaults to `false` to maintain the current CATS behavior.
- modifies the routing transparency CATS to allow for Istio Proxy's URL
normalization
Story: https://www.pivotaltracker.com/story/show/169404143
We've run the …

assert different "routing transparency" behavior for Istio Proxy

---

apps/syslog_drain.go
assets/syslog-drain-listener/syslog_drain.go
isolation_segments/isolation_segments.go
tasks/task.go

This PR consists of three commits that can be reviewed in isolation.  The commit message of each change explains the intention behind the change.
We intend to run CATs in our managed environment on AWS.
https://vmware.slack.com/messages/C3LUD2L04/p1602100943001300
CATs 5.11.0
I think the three commit messages are good candidates since they are descriptive and brief.  I will include them below:
```
Use https syslog drain URL instead of syslog-tls.
Use Config.Protocol() instead of hard coding the protocol.
Fix the test to reflect the original intention.
```
This change will make CATs faster since the Syslog test was simplified and doesn't wait or parse the Syslog listener logs anymore.
@Logiraptor @houlistonm

Fix CATs to allow it to run in more configuration

---

assets/dora/dora.rb

- Useful for tracking if and when dora restarted
Authored-by: Greg Cobb <gcobb@pivotal.io>
Yes
CAPI is starting a track of work to avoid unexpected downtime when updating apps.
Relevant proposal: https://docs.google.com/document/d/1xMJ6dVSmELHmYAqr9bRIFyBHEfWPbswqwvEuv3bP4D4/edit
N/A
N/A
N/A
N/A

Add uptime counter to dora

---

route_services/route_services.go

Yes
Fixing CATS against V8 CLI
The bind-route-service command is being specified with the obsolete -f
flag. This was disabled in 2016 in such a way that it would just be
ignored. The V8 CLI will remove it completely, but since it's not
actually done anything for years, it makes sense to remove the usage
completely, as it's not testing anything meaningful.
Flag disabled here: https://github.com/cloudfoundry/cli/commit/6cb7db9de2d6bbf4c353e999bc0b4906f0582e18
Flag removed in V8 here: https://github.com/cloudfoundry/cli/commit/e8e8a3874c7864d8b7e1a48c96b458e8ea7c6a4e
_Include any links to other PRs, stories, slack discussions, etc... that …

route_services: remove obsolete flag

---

assets/dora/Procfile

* change Dora to listen on 0.0.0.0 instead of `localhost`.
Listening on `localhost` prevents outside connections reaching to dora
without proxying through local gateway. In case of cf-for-k8s if Dora is
pushed to the cluster without sidecar injection it cannot accept
connections without this change.
While working on adding support to Contour in cf-for-k8s we found out that many pods were failing to accept connections. With Istio all workload pods have injected Envoy sidecar which will proxy all connections to the app container through the local container network. Without the sidecar the connection will be sent over Kubernetes services network. And if the application is not accepting those IP addresses it cannot work in the cluster.
In addition, without this change `tcp` readiness probes …

Dora: accept connections from all addresses

---

README.md
app_syslog_tcp/syslog_drain.go
cats_suite_helpers/cats_suite_helpers.go
cats_suite_test.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go

Yes
This change moves the `syslog drain` test to a separate suite to allow it to be skipped while still running the majority of the `apps` suite.
The original request to update this test to always use TLS came from PR #441. This was reverted via https://github.com/cloudfoundry/cf-acceptance-tests/commit/7e1089ca9c538664f3b77293e53380b954abc1dc due to CI failures. After discussions with @jvshahid, we decided to move the test to a separate suite to allow it to be skipped.
v15.0.0
Moved the syslog drain test to a new suite to allow it to be skipped on environments that do not allow internal TCP traffic.
@jamespollard8

Split the syslog drain test into a separate suite

---

services/service_instance_lifecycle.go

we do not print it if the job is already completed when we first poll.
[#175617691](https://www.pivotaltracker.com/story/show/175617691)
Remove check on "Binding in progress" message from async bind/unbind.
When v8 cli gets a 202 response for binding/unbinding, it first polls the api job for status and doesn't print any messages until the job is either in polling state or completed.
In the current broker implementation, last operation for service bindings will always return completed (never in progress) so the whole job finishes almost instantly and it's completed by the time the cli requests the last operation status.
The "binding in progress" message only gets printed if the job …

Remove check on 'binding in progress' message for async bind/unbind as

---

.gitmodules
assets/logging-route-service/.gitignore
assets/logging-route-service/LICENSE
assets/logging-route-service/README.md
assets/logging-route-service/main.go
assets/logging-route-service/manifest.yml
vendir.lock.yml
vendir.yml

Yes
This PR changes the way we vendor `assets/logging-route-service/`.  Instead of using git submodules, the assets are now vendored using [vendir](https://github.com/vmware-tanzu/carvel-vendir).  This change makes it possible to download a self-contained CATs zip file from the Github releases page.  Previously the CATs zip file would be missing the asset mentioned before.
https://vmware.slack.com/archives/C3LUD2L04/p1606239248053300
I didn't run the tests.
Vendor `assets/logging-route-service` using [vendir](https://github.com/vmware-tanzu/carvel-vendir).
Zero.

Use vendir to vendor the logging-route-service sample app

---

route_services/route_services.go

⚠️⚠️⚠️⚠️ This PR will fail until a new version of routing release is cut. This will likely be 0.211.0.
Yes
Adding new cat for route service with sticky sessions.
* [#175826411](https://www.pivotaltracker.com/story/show/175826411)
v15.5.0
All tests for sticky session and route services are already in CATs. This CAT proves that these two features work together.
add new cat for route service with sticky sessions
It's a new CAT that pushes an app and a route service. Likely ~200.
@cloudfoundry/runtime

Add new cat for route service with sticky sessions

---

routing/multiple_app_ports.go

Yes.
CAPI has been working on implementing zero downtime updates for certain attributes, one of which is changing an app's ports. Making changes to an app's ports now requires a restart for the changes to take effect. 
This commit reflects that change by adding a `cf restart --strategy rolling` to the "Multiple App Ports" test.
Link to the tracker epic: https://www.pivotaltracker.com/epic/show/4691338
Latest release candidate (https://github.com/cloudfoundry/cf-deployment/commit/0cb79eba4528ce34dad24a7e1271bc3a0492345f).
May be worth calling out this new behavior for future test contributors, but nothing required for this immediate change.
+10 seconds
@sweinstein22

Add a restart to multi-port test

---

helpers/services/sso.go

* The test was expecting the UAA authorization code to only contain
letters and numbers, which was a incorrect expectation. For example,
as of today, the code can contain dashes "-".
* The regex was updated so that the code can contain any character. If
the UAA decides one day to add another CGI parameter to the redirect
URL, the test won't break because of the "^&" in the regex.
* The '\r' and '\n' are there to end the regex match at the end of the
line.
* For context, this is what an UAA API response looks like. See line 6
the code we are trying to extract.
HTTP/2 302
cache-control: no-store
content-language: en-US
content-length: 0
date: Tue, 02 Feb 2021 22:10:17 GMT
location: http://example.com?code=gfCMdm9L3P                # <- code here
strict-transport-security: max-age=31536000 …

UAA v75 CAT flakes

---

apps/lifecycle.go

We recently changed the process stats endpoint to return the actual disk and memory quotas rather than the desired quotas from the cloud controller database. When these metrics have not been propagated to log cache, ccng returns zeros, and the CLI does not display units.
Associated Github Issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/2098
Latest
N/A
0 seconds
@sethboyles @tstannard @elenasharma

Make app summary memory and disk units optional

---

services/service_instance_sharing.go

[#176882923](https://www.pivotaltracker.com/story/show/176882923)
v8 CLI output has changed for services. This fix should make CATs pass for [v8 CLI](https://ci.cli.fun/teams/main/pipelines/v8/jobs/cats/builds/184.1). 
[#176882923](https://www.pivotaltracker.com/story/show/176882923)
[v8 CLI pipeline](https://ci.cli.fun/teams/main/pipelines/v8/jobs/cats/builds/184.1)
- [] **Urgent** - unblocks current or future work
@cloudfoundry/services-api

Update result for v8 service output

---

helpers/services/broker.go
services/service_broker_lifecycle.go
services/service_instance_lifecycle.go

[#177245959](https://www.pivotaltracker.com/story/show/177245959)
Services test relly only on v3 CAPI endpoints.
v16.5.0
Services test relly only on v3 CAPI endpoints.

Replaced all v2 API calls with v3 calls

---

services/service_broker_lifecycle.go

Schema changes are backwards incompatible causing this test to fail in pipelines where CAPI has not been updated to latest.
See more: https://vmware.slack.com/archives/C3LV25ZCM/p1616791595072300 
[slack discussion](https://vmware.slack.com/archives/C3LV25ZCM/p1616791595072300)
@JenGoldstrich

Commenting out broker schema assertions.

---

services/service_broker_lifecycle.go

Reverts cloudfoundry/cf-acceptance-tests#464
Fixed in capi v1.109.0

Revert "Commenting out broker schema assertions."

---

cats_suite_helpers/cats_suite_helpers.go
helpers/skip_messages/skip_messages.go
isolation_segments/isolation_segments.go
tcp_routing/tcp_routing.go

Adds tests to ensure that TCP routed apps work on isolation segments (but not for routed isolation-segments)
https://www.pivotaltracker.com/story/show/178937872
https://github.com/geofffranks/cf-deployment/tree/tcp-isolation / https://github.com/cloudfoundry/cf-deployment
Only runs the new test when both tcp_routing + isolation_segment suites are included
This test is only enabled when both tcp_routing and isolation_segments are included, and seems the best place to test a CloudFoundry environment using both of these features.
Adds tests to validate that TCP routed applications function when deployed on a shared-routing isolation segment.
~300 seconds (3 tests, 2 app pushes) when both TCP routing + isolation segments are included in the test.
_It's helpful to tag a few other folks on your …

[#178937872] Adds TCP routing tests to apps on isolation segments

---

cats_suite_helpers/cats_suite_helpers.go
helpers/skip_messages/skip_messages.go
isolation_segments/isolation_segments.go
tcp_routing/tcp_routing.go

Reverts cloudfoundry/cf-acceptance-tests#474
- we saw repeated failures in CI (for example, see https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/upgrade-cats/builds/3204)

Revert "[#178937872] Adds TCP routing tests to apps on isolation segments"

---

README.md
cats_suite_helpers/cats_suite_helpers.go
cats_suite_test.go
example-cats-config.json
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go
user_provided_services/lifecycle.go

Add tests for user-provided service operations
As part of fixing https://github.com/cloudfoundry/cloud_controller_ng/issues/2543 it is useful to have some CATs that exercise the user-provided service behaviour. In particular the test that service bindings get updated when the service gets updated will currently fail on `cf8` due to the CC v3 endpoint not having the correct behaviour.
Given these are dedicated user-facing commands on the CLI (`cf cups` and `cf uups`), I figured it made sense to have some CATs to cover their behaviour
Latest (v16.25.0)
Add tests for user-provided service operations
~60s with 4 nodes (slowest test is 60 seconds, fastest are <2 seconds)
Working with team at SAP (can contact @philippthun, @FloThinksPi or @stephanme for followup)

Add tests for user-provided services

---

assets/service_broker/README.md
assets/service_broker/setup_new_broker.rb

Yes
Updates the setup_new_broker.rb script used to bootstrap the test service broker.
The script used the now-defunct '-d' flag for cf push, which was deprecated in version 7 of the cf CLI. As it is no longer possible to specify an app's domain via commandline flags in a 'cf push', the script has been updated to retrieve the route of the test broker after it has been deployed. It then uses this to register the broker.
n/a
n/a
n/a
n/a
@SAP/cf-controlplane

Drop -d flag no longer supported after cf6

---

assets/proxy/main.go
service_discovery/service_discovery.go

YES
Adds test for C2C over TLS, new feature available in diego-release [v2.59.0](https://github.com/cloudfoundry/diego-release/releases/tag/v2.59.0)
https://github.com/cloudfoundry/diego-release/issues/587
cf-deployment did not pick up the latest diego-release yet. We have run it with latest cf-deployment and diego-release v2.59.0
We want to make sure C2C is working not just over HTTP but HTTPS as well.
New test for container to container networking over TLS
56s
@cloudfoundry/cf-diego

Add a test for C2C over TLS

---

credhub/service_bindings.go

Fixes a credhub test that fails intermittently.
[179005915](https://www.pivotaltracker.com/story/show/180465755)
latest
Fixes a credhub test that fails intermittently.
Maybe 10 seconds as the test polls for output. There's a 3-minute timeout if the test fails.
@bruce-ricard @peterhaochen47

Service bindings test flake fix [179005915] 

---

routing/session_affinity.go
v3/app_lifecycle.go

Yes
Clean up code where packages are imported twice (as a dot import and regularly):
* `routing/session_affinity.go`
* `v3/app_lifecycle.go`
Decided to remove the dot imported packages for more idiomatic go.
N/A
None
N/A
N/A
None
N/A

Fix: double imports

---

apps/default_environment_variables.go
assets/loggregator-load-generator-go/loggregator-load-generator.go
helpers/v3_helpers/v3.go
routing/multiple_app_ports.go
services/service_instance_lifecycle.go

Yes
Gets closer to idiomatic code by removing alot of unnecessary usage of `fmt.Sprintf`.
N/A
None
N/A
N/A
None
N/A

Remove unnecessary fmt.Sprintf usage

---

apps/instance_reporting.go
ci/pipeline.yml

This PR updates the memory resource scaling test to be skipped when the `infrastructure` config option is set to `Kubernetes`.
This test fails often but is not worth changing now that cf-for-k8s is not under active development.
N/A
Skip the memory resource scaling test when the `infrastructure` config option is set to `Kubernetes`.
N/A
@acosta11 @Birdrock @ctlong

Skip the memory resources test on K8s

---

security_groups/running_security_groups.go
tasks/task.go

Update cats-dynamic-asgs PR branch with fixes for existing ASG tests in a DASG env
Fixes failures seen for #501 
latest 
Up to 9 mins with the eventually statements, but with the use of cf-deployment/operations/test/speed-up-dynamic-asgs.yml that should be drastically reduced (mins -> seconds)
@ctlong @davewalter

Update cats-dynamic-asgs PR branch with fixes for existing ASG tests in a DASG env

---

helpers/config/config_struct.go

* Avoids possible false pass
Co-Authored-By: Bruce Ricard <bricard@vmware.com>
Fixes what appears to be a typo in the logic that makes the test less effective than intended.
Fixes what appears to be a typo in the logic that makes the test less effective than intended.
None.
@bruce-ricard

fix: faulty test logic

---

assets/proxy/main.go
security_groups/dynamic_asgs.go
security_groups/running_security_groups.go
tasks/task.go

Yes
Acceptance tests for Dynamic ASGs, to be enabled by default in cf-deployment.
https://www.pivotaltracker.com/story/show/181363273
v18.0.0 with silk-release update to v 3.0 and policy-server-asg-syncer enabled with this ops file: https://www.pivotaltracker.com/story/show/180837394/comments/229193630
xCATs should validate common operator workflows._
Add a test for dynamic (no restart) security groups.
3 mins

Add a dynamic ASG test to the security_groups test suite

---

http2_routing/http2_routing.go

Yes
`grpc.Dial` with `grpc.WithTimeout` is deprecated and should be replaced
by `grpc.DialContext` with a context that has a timeout.
Closes #489 
https://pkg.go.dev/google.golang.org/grpc#WithTimeout
v20.2.0
N/A
None
N/A

Fix: stop using deprecated grpc.WithTimeout

---

tasks/task.go

The current "binding a space-specific ASG" test fails approximately 80%
of the time on a vanilla Cloud Foundry deployment. In a nutshell, the
new space-specific ASG has not propagated by the time that the app has
restarted, and the app is beholden to the old ASGs: What should be a
timeout is a "connection refused".
This commit fixes that by inserting a 60-second delay between
setting the new ASG and restarting the app. The 60-second delay is not
arbitrary; rather, it is the result of the meticulous gathering of
empirical data presented in the chart below:
|Delay (seconds)|# of tests|Success Rate (%)|Success Rate Histogram     |
|--------------:|---------:|---------------:|:--------------------------|
|             0 |       60 |             20 | *****                     |
|             5 …

Reduce flakiness of space-specific ASG test

---

http2_routing/http2_routing.go

We found that the 1 second timeout for establishing a GRPC connection was too aggressive for our Nimbus/vSphere test environments.  Increasing this timeout to 5 seconds allowed our tests to pass reliably.
We debugged this failure in a Pivotal Tracker story [here](https://www.pivotaltracker.com/story/show/182068985).
This was failing against TAS 2.11 and above.
We are running off a fork with this change but would like to return to consuming upstream cloudfoundry/cf-acceptance-tests.
@crhntr

Increase HTTP/2 Routing GRPC context timeout

---

services/service_instance_lifecycle.go

Co-authored-by: Seth Boyles <sboyles@pivotal.io>
Co-authored-by: Alex Rocha <alexr1@vmware.com>
Yes
An upcoming change in capi no longer pretty prints json responses from cc api. This change updates a test that was dependent on a pretty printed response from ccapi.
Details below:
https://github.com/cloudfoundry/cloud_controller_ng/pull/2930
https://github.com/cloudfoundry/capi-release/issues/262
Release Candidate
@sethboyles @xandroc

Using json matcher instead of string matcher to validate api response

---

helpers/v3_helpers/routes.go

Co-authored-by: Seth Boyles <sboyles@pivotal.io>
Co-authored-by: Merric de Launey <mdelauney@pivotal.io>
Co-authored-by: David Alvarado <alvaradoda@vmware.com>
Similar to https://github.com/cloudfoundry/cf-acceptance-tests/pull/587, this test is failing on latest CAPI since it is parsing JSON responses as strings (considering whitespace, etc).
https://github.com/cloudfoundry/cloud_controller_ng/pull/2930
https://github.com/cloudfoundry/capi-release/issues/262
release-candidate
n/a
@xandroc 
@MerricdeLauney 
@dalvarado

Unmarshal Route JSON instead of parsing as a string

---

assets/service_broker/service_broker.rb
assets/service_broker/spec/service_broker_spec.rb
helpers/services/broker.go
helpers/services/sso.go
services/sso_lifecycle.go

Yes
Broadly, two changes. Both are related to the sso (services) test suite, which tests the [single sign-on lifecycle for service dashboards](https://docs.cloudfoundry.org/services/dashboard-sso.html).
1. Updates the helper `QueryServiceInstancePermissionEndpoint` to hit `/v3/service_instances/:guid/permissions` instead of its v2 equivalent. We recently found that the suite would fail with v2 of the CF API disabled, and were surprised to find there was no v3 equivalent of `/v2/service_instances/:guid/permissions`, which we've now implemented (see cloudfoundry/cloud_controller_ng#2946)
2. Updates the way the tests get the CF API's info endpoint, which is needed as part of the SSO OAuth flow. The CATS service broker will now grab the CF API info endpoint from the [X-Api-Info-Location …

Test new /v3/service_instances/:guid/permissions

---

apps/lifecycle.go
apps/log_rate_limit.go
cats_suite_test.go
windows/lifecycle.go

Yes.
The cf CLI, Cloud Controller API and Diego are being extended with support for defining log rate limit quotas. This PR adds tests to confirm that basic log rate limiting is working correctly. 
We added examples to the apps and windows tests.
We did not add tests for creation of quotas with an associated log rate limit.
For these tests to run the `minCliVersion` was updated to a version of the cf CLI that supports specifying a log rate limit when pushing an application.
This shouldn't be merged before [capi >= 1.137.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.137.0) is in cf-deployment release-candidate branch.
* [Proposal doc](https://docs.google.com/document/d/1BEdtKHJ877Cn4HOfvAzIdMwoD0dpZuzRNBsmQ7c5_zM/edit#heading=h.sa8b0ujnd2tn)
* …

Add tests for log rate limiting

---

user_provided_services/lifecycle.go

In some scenarios, CAPI returns an empty 'syslog_drain_url' field in addition to the credentials. The MatchJSON matcher is fairly strict -- if there are additional fields to what is specified, it will fail. This change makes the targeted assertion that the test actually cares about -- that the username is properly stored in the credentials.
N/A
v21.8.0
N/A
None

Make a more targetted assertion in the user_provided_services lifecycle test

---

services/service_instance_lifecycle.go
user_provided_services/lifecycle.go

Generates a random name for a test artifact instead of using a hard-coded one.
Sometimes when tests are canceled (e.g. by a developer using Ctrl-C), artifacts get littered. The left behind artifacts, in conjunction with not using unique names, made tests fail.
v21.8.0
N/A

Randomize names in rename test to avoid name collisions during parallel test runs or runs on environments with littered service instances

---

apps/lifecycle.go
windows/lifecycle.go

Yes.
* Apps that aren't logging anything don't show a log rate greater than zero.
* Added a call to logspew in the polling so the app summary displays a log rate over zero.
* Also combined some tests to speed things up that were testing three things about the same output.
* Removed one SkipOnK8s call so we could merge tests.
N/A
None.
Should save about 2 minutes because we combined tests.
@rroberts2222

Fix: log rate limiting lifecycle tests

---

README.md
detect/buildpacks.go
helpers/config/config_struct.go
helpers/config/config_test.go

Add "cflinuxfs4" to list of allowed stacks.
https://github.com/cloudfoundry/cf-acceptance-tests/issues/642
https://github.com/cloudfoundry/cf-deployment/releases/tag/v23.3.0
Depends on list of "stacks" configured. Difficult to estimate as not many tests really use the "stacks" property.

Add cflinuxfs4 to list of stacks

---

README.md
assets/nginx/nginx.conf
assets/r/Procfile
assets/r/simple.r
detect/buildpacks.go
helpers/assets/assets.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go

Additional tests for r_buildpack and nginx_buildpack, in particular to test the new cflinuxfs4 stack.
https://github.com/cloudfoundry/cf-deployment/issues/989
v23.3.0
We want to verify that all buildpacks that come with cf-deployment support the new cflinuxfs4 stack. This is tested in the cf-deployment pipeline here:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4
Execution times were measured on https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats
Before (229 specs): 39min 30sec average
After (331 specs): 37min
Looks like CATs on a warmed up CF run a bit faster... I would have expected a slight increase as we do 2 additional cf pushes.
_It's helpful to tag a …

Additional tests for r_buildpack and nginx_buildpack

---

apps/default_environment_variables.go
apps/lifecycle.go
isolation_segments/isolation_segments.go
routing_isolation_segments/routing_isolation_segments.go
v3/app_lifecycle.go
v3/buildpacks.go

Signed-off-by: Aram Price <pricear@vmware.com>
Some tests are still using hard-coded values to refer to buildpack names. These values can be retrieved from the Config object. Using the Config object in all places ensures that modifying the Config results in consistent behavior throughout CATs.
v24.6.0
N/A
None
@aramprice

Use configurable buildpack names instead of hard-coded strings

---

assets/java-spring/.gitignore
assets/java-spring/README.md
assets/java-spring/pom.xml
assets/java-spring/src/main/java/org/cloudfoundry/SpringBootTrivialApplication.java
helpers/assets/assets.go

This will allow the asset to be rebuilt or updated as needed, while still providing a .jar file so that a Java toolchain is not needed to run CATs
Signed-off-by: David Sabeti <sabetid@vmware.com>
v24.6.0
N/A
N/A
@aramprice

Replace old java-spring asset with a new asset that also includes source code

---

routing/zipkin_tracing.go

This is causing failure on go 1.19
Signed-off-by: Marc Paquette <mpaquette@vmware.com>
Yes
Remove trailing space in the Zipkin header X-B3-TraceId. Looks like a typo. This is causing test failures in go 1.19.4.
This test was run against TAS 4.0.0

Remove extra space from zipkin header

---

app_syslog_tcp/syslog_drain.go
assets/syslog-drain-listener/syslog_drain.go

use tcp routes for syslog tests rather then sketchy internal routes
It's the reliable and canonical way to setup a cf app that recieves tcp traffic. No reason to test this feature against "internal routing"
v24.6.0
N/A
Shouldn't really make a difference I think. 
@cloudfoundry/wg-app-runtime-platform-logging-and-metrics-approvers
@cloudfoundry/wg-app-runtime-platform-logging-and-metrics-reviewers

Feat: use TCP routes for app syslog drain tests

---

README.md

#704 removed this script but missed it in beginning of the readme
Yes
I got confused reading the readme trying to update submodules that didn't exist
#704 made the change and just missed a spot
I didn't cause it is a readme change
I am not introducing a new acceptance test
Hopefully no change
_It's helpful to tag a few other folks on your team or your team alias in case …

Remove `update_submodules` reference in README

---

README.md
ci/cats.md
docs/run-on-k8s.md
helpers/config/config_struct.go
helpers/config/config_test.go

Yes, however, this change does depend on first merging https://github.com/cloudfoundry/cf-acceptance-tests/pull/697.
The `php_buildpack_name` field is never used by CATs, so this PR removes all references to it. In fact, despite having this configuration parameter, the Config _interface_ does not expose a `GetPhpBuildpackName()` function as it does with most other buildpacks, so we know programatically that this field is never used.
(The PHP asset is used only in the `detect` test suite, where no buildpack name is specified on purpose -- the test exists to validate that a PHP app is successfully detected by CF even when the user does not explicitly specify a buildpack.)
N/A
N/A
N/A
N/A
@aramprice

Remove php buildpack config

---

README.md
ci/cats.md
docs/run-on-k8s.md
helpers/config/config_struct.go
helpers/config/config_test.go

Yes, however, this change does depend on first merging https://github.com/cloudfoundry/cf-acceptance-tests/pull/697.
The `python_buildpack_name` field is never used by CATs, so this PR removes all references to it. In fact, despite having this configuration parameter, the Config _interface_ does not expose a `GetPythonBuildpackName()` function as it does with most other buildpacks, so we know programatically that this field is never used.
(The Python asset is used only in the `detect` test suite, where no buildpack name is specified on purpose -- the test exists to validate that a Python app is successfully detected by CF even when the user does not explicitly specify a buildpack.)
N/A
N/A
N/A
N/A
@aramprice

Remove python buildpack config

---

ci/pipeline.yml

Yes
Removes unused task deliver-tracker-story from cats pipeline. This task is an artifact of when the folks managing this repo used a public tracker project. We've since switched to using GH projects.
- [slack thread](https://cloudfoundry.slack.com/archives/C033ALST37V/p1675323741810389)
N/A - this is a CI-only change
N/A
None
None

CI: remove unneeded task to deliver tracker stories

---

cats_suite_test.go

Yes.
[Recent changes in Go 1.20](https://go.dev/doc/go1.20#go-command) mean that if the machine where CATs is running has a newer version of glibc than Cloud Foundry then catnip will fail to push.
Fixes the following errors pushing catnip when compiling with Go 1.20:
```
[APP/PROC/WEB/0] ERR ./catnip: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./catnip)
[APP/PROC/WEB/0] ERR ./catnip: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./catnip)
```
https://go.dev/doc/go1.20#go-command
None
N/A
N/A
@ctlong

Compile catnip with CGO_ENABLED=0

---

assets/catnip/go.mod
assets/credhub-service-broker/go.mod
assets/go_calls_ruby/go.mod
assets/golang/go.mod
assets/grpc/go.mod
assets/http2/go.mod
assets/logging-route-service/go.mod
assets/pora/go.mod
assets/proxy/go.mod
assets/syslog-drain-listener/go.mod
assets/tcp-listener/go.mod
assets/worker-app/go.mod
assets/worker/go.mod
go.mod

Yes
Replaces go1.18 with go1.19 wherever possible, as go1.18 is out of support. We want to encourage folks to use at least go1.19.
None
None
No
None
None

Fix: bump min go versions in go.mod files

---

README.md
helpers/config/config.go
helpers/config/config_struct.go
security_groups/dynamic_asgs.go

Yes
Enables negative testing of dynamic asgs (ensuring that when disabled dynamic updates are not applied)
Based on the tests in 
Latest toolsmiths cf-deployment
Not sure if this requires an update to integration-config. If CATS is run against an environment with dynamic asgs disabled, and the security group testing enabled, you must also specify `dynamic_asgs_enabled: false` in your test config. When dynamic asgs is enabled (on by default), no changes are needed.
No new tests
Should not change the runtime for CATS under default circumstances. When dynamic asgs is enable, the test does not change. When disabled, it takes the same time as when enabled.

Add support for positive + negative dynamic ASG tests

---

cats_suite_test.go
helpers/config/config_struct.go
helpers/config/config_test.go

Yes
Error out on invalid timeout scale rather than quietly correcting it to one. This is a breaking change.
I think this is useful to provide clarity to operators that their configuration is incorrect rather than silently choosing some value. If operators don't want to overwrite the timeout scale value, then they can remove the field from the JSON altogether, as there's a default value of 2.
None
v26.4.0
N/A
None
None

Fix: error on incorrect timeout scale

---

internet_dependent/git_buildpack.go

Yes
Fixing CATs on cf-d with cflinuxfs4 set as the default stack.
* We are using a pinned buildpack to avoid potential instability issues. See 508d675 for previous bump.
v26.5.0
N/A
None
None

Bump nodejs-buildpack to version that supports cflinuxfs4

---

assets/catnip/go.mod
assets/credhub-service-broker/go.mod
assets/go_calls_ruby/go.mod
assets/golang/go.mod
assets/grpc/go.mod
assets/http2/go.mod
assets/logging-route-service/go.mod
assets/pora/go.mod
assets/proxy/go.mod
assets/syslog-drain-listener/go.mod
assets/tcp-listener/go.mod
assets/worker-app/go.mod
assets/worker/go.mod
go.mod

Yes
Updates all go modules across CATs to specify go 1.20 as the version to use.
None
v26.4.0
N/A
None
None

Fix: Use go 1.20

---

apps/renaming.go
helpers/logs/logs_helper.go
helpers/v3_helpers/v3.go
v3/buildpacks.go

Yes.
- Logs that are emitted by a renamed app are tagged with the new name without requiring a restart.
- Check the origin of the emitted log as the cloud controller will emit logs against the new app name when the rename is performed.
- Move recent logs function to the logs helper.
The new test is dependent on PRs opened against Diego and CAPI which have not yet been merged. This PR should not be merged prior to release of the Diego and CAPI changes.
This is a breaking change as it requires those new versions of Diego and CAPI.
cloudfoundry/diego-release#662
None
This is testing a common operator workflow.
45 seconds more.
@ctlong

Add test for app renaming

---

helpers/logs/logs_helper.go

Yes
Fix failing [app renaming tests](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cats/jobs/run-cats-vms/builds/39) by fetching the latest 1000 envelopes from Log Cache rather than the eldest 1000 envelopes.
Unless [descending=true](https://github.com/cloudfoundry/go-log-cache/blob/b2a3593e6ad7a66e451e3c67b067a064a20a5a1c/api/v1/egress.proto#L30) is included in the Log Cache request, then Log Cache purposefully returns the eldest envelopes in Log Cache from the [start_time](https://github.com/cloudfoundry/go-log-cache/blob/b2a3593e6ad7a66e451e3c67b067a064a20a5a1c/api/v1/egress.proto#L26).
In the case of our tests that utilize `logs.RecentEnvelopes()` we would like to fetch the most recent envelopes.
v27.1.0
N/A
None
@acrmp

Fix: log fetching

---

tasks/task.go

* The version of `curl` that we get in cflinuxfs4 appears to have a
different error message when the connection times out.
* The error code is consistant accross versions, so use it.
Authored-by: Steve Taylor <sttaylor@vmware.com>
Yes.
It appears that the `curl` that ships with cflinuxfs4 outputs a different string
when a connection fails.  The test is too specific, so we've added a match for
the curl error code (which has remained consistant).  The test now passes against
tas `rel/4.0`.
No further context available.
TAS 4.0.0 beta - we have not tested against cf-deployment yet, but the change is
additive, so we do not expect a difference in behavior for cf-deployment.
No meaningful change (sub milisecond)
#platform-provider-experience
@sttaylor
@dsabeti

fix: use curl error code to determine failure

---

go.mod
go.sum
helpers/config/config.go
helpers/config/config_struct.go
vendor/github.com/cloudfoundry/cf-test-helpers/v2/workflowhelpers/internal/cf_auth.go
vendor/github.com/cloudfoundry/cf-test-helpers/v2/workflowhelpers/internal/user.go
vendor/github.com/cloudfoundry/cf-test-helpers/v2/workflowhelpers/user_context.go
vendor/modules.txt

Yes
Bumps cf-test-helpers. This PR supersedes https://github.com/cloudfoundry/cf-acceptance-tests/pull/746, as it brings in changes to the config necessary because of https://github.com/cloudfoundry/cf-test-helpers/pull/92.
None
None
N/A
None
None

Fix: bump cf test helpers

---

apps/buildpack_cache.go

Ja
Set CF Push timeout explicitly for flaky test.
https://cloudfoundry.slack.com/archives/C033ALST37V/p1681475952423619
@jochenehret

Set CF Push timeout explicitly for flaky test

---

apps/buildpack_cache.go

Fix a Flaky test
Yes
Hardcode CF push timeout to 120 seconds for a flaky test(buildpack_cache).
https://cloudfoundry.slack.com/archives/C033ALST37V/p1681475952423619
N/A
@jochenehret

Hardcode CF push timeout to 120 seconds for builpack_cache tests.

---

apps/buildpack_cache.go

Yes
Removes `cf push` timeout added in #831 and #832.
This test was quite flakey at the time and this timeout was added in an attempt to stabilize it. The test has since stabilized. However, the cause of the failure appears to be tied to a bug in GoRouter, which was claimed to have been resolved in routing release v0.263.0.
We want to remove this hardcoded timeout now and see if the test is still stable with the new, fixed routing release.
* https://cloudfoundry.slack.com/archives/C033ALST37V/p1681340479165379?thread_ts=1680888356.483179&cid=C033ALST37V
* https://github.com/cloudfoundry/routing-release/releases/tag/v0.263.0
None
N/A
None
None

Fix: Update apps/buildpack_cache test

---

security_groups/dynamic_asgs.go

Yes
Change test for non-dynamic ASGs to use a sleep instead of Consistently because of intermittent connectivity issues.
While running `acceptance-tests` for `cf-networking-release` in ci, the `cats` section would error saying `connection refused`.  When we ran the tests manually we were unable to reproduce.  When repeating the test at 0.1s, we saw intermittent connection issues with ASGs. This new timeout should help prevent the connection error.
I believe v27.6.0.  It was a toolsmiths environment using the cf-deployment pool.
N/A
Hopefully no changes, but should make the test less flaky so we won't have to do multiple runs.
@reneighbor @geofffranks  @cloudfoundry/wg-app-runtime-interfaces

asg timeout

---

v3/buildpacks.go
v3/deployment.go
v3/droplet.go
v3/healthcheck.go
v3/process.go

There are several tests that start an app, stage an app, or trigger CF to restart an app. In all of these cases, we should use the CfPushTimeoutDuration, because that duration is set aside specifically for events like these
N/A
N/A
This test changes some timeouts from 30 seconds to 240 seconds (or 4 minutes). There are 12 `Eventually`s changed in this commit. As such, in the worst case scenario, this could add up to (240-30)*12 = 2,520 seconds (or 42 minutes).
In all likelihood, this will not increase run time much for most consumers of CATs. In fact, it will only increase the runtime in cases where the tests were failing due to a timeout. So this is a trade between run time and robustness of the test suite to flakiness.
_It's helpful to tag a few other folks on your team or your team …

v3 suite: use CfPushTimeotDuration where appropriate

---

assets/credhub-service-broker/handlers.go
assets/credhub-service-broker/main.go
assets/credhub-service-broker/manifest.yml
credhub/service_bindings.go
credhub/service_keys.go
docker/credhub_enabled.go
windows/credhub_assist.go

Yes
Refactors the credhub-service-broker asset for clarity, and to handle errors better. We were seeing a good amount of pipeline flakes recently that were resulting from the app going into a panic off one-time failures to connect to CredHub.
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/upgrade-cats/builds/340
v29.1.0
N/A
Actually knocks about 2 seconds off the runtime per test using this app because of the switch from restarting to starting. Not including the windows suite this amounts to about 16 seconds total.
None

Fix test flakiness resulting from credhub-service-broker asset's improper error handling

---

README.md
helpers/config/config_struct.go
helpers/config/config_test.go

Allows users to specify values other than `cflinuxfs4` in the config's `stacks` field.
Given recent efforts to integrate elements of the CNB ecosystem into CF -- in particular, [this proposal to integrate Paketo stacks](https://github.com/cloudfoundry/community/pull/637) -- CATs should allow operators to specify additional stacks besides cflinuxfs4.
N/A
N/A
@Gerg

Allow all stacks

---

ci/cats.md
ci/pipeline.yml

As discussed in the ARD WG meeting from Jul 27th, we want to rework the CATs release pipeline:
* use cats-develop branch as main trigger
* first run unit tests as sanity check
* then deploy cf from cf-deployment "main" branch
* run smoke-tests and then the actual CATs tests
* finally, cleanup CATs and destroy cf again to save cost
Note that the smoke-tests pipeline already uses a separate bbl infrastructure (was shared with CATs before).
As the pipeline.yml diff is likely not easy to read, I've uploaded the new pipeline (in paused state) here:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cats-new
(not relevant)

Rework cats pipeline

---

routing/zipkin_tracing.go

Increase readiness timeout for Spring Sleuth app in Zipkin Tracking tests. This should hopefully reduce test flakes in this suite.
Also refactors the zipkin tests, just cause.
#862 
v29.1.0
N/A
None
None

fix(zipkin): increase app readiness timeout to reduce test flakes

---

assets/dora/readiness_manifest.yml
assets/nora/readiness_manifest.yml
windows/readiness_healthcheck.go

✅  yes.
Fixing [this failure](https://github.com/cloudfoundry/cf-acceptance-tests/issues/922) caused by [this PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/915).
* [Previous PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/915)
* [CI failure](https://github.com/cloudfoundry/cf-acceptance-tests/issues/922)
* [Slack convo](https://cloudfoundry.slack.com/archives/C033ALST37V/p1692900806935289?thread_ts=1692285983.883259&cid=C033ALST37V)
https://github.com/cloudfoundry/cf-deployment/releases/tag/v32.2.0
Now tests will pass :) 
_It's helpful to tag a few other folks on your team or your team alias …

Remove stacks from readiness manifests

---

bin/test

Yes
`./bin/test` should:
- Randomize all specs. This helps suss out spec pollution.
- Instruct Ginkgo to keep running suites even after a suite fails. This makes sure we get the full set of failures on a test run.
None
None
N/A
None
None

Chore(bin): update test defaults

---

apps/readiness_healthcheck.go
apps/rolling_deploy.go
v3/deployment.go
windows/readiness_healthcheck.go

Yes
Our helpers only return response bodies, not response statuses. This means that if we want to check for a 404 error, for instance, we need to check the body for a 404 error. However, some operators override their router's error pages, which break our expectations, if they're too specific.
This makes our 404 expectations less specific by reducing our assumptions about the error page returned from "it contains `404 Not Found`", to "it contains `404`". The latter seems like a pretty safe assumption to make.
Closes #929 
None yet
N/A
None
None

Fix: 404 expectations for custom router error pages

---

README.md

As stated in the [Go Modules Reference](https://go.dev/ref/mod#go-mod-file-go), it must be at least the version declared in the go directive.
So, I have matched the minimum version of go in the README to the version defined in go.mod.

Update minimum go version to 1.20

---

apps/loggregator.go

Provide better error message if the firehose websocket connection cannot be established.
The problem can occur if you use an AWS classic load balancer and you don't change the doppler ports with the [aws.yml ops file](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/aws.yml).
v33.9.0
Test will fail faster if websocket connection cannot be established.

Check error when we try to open the firehose websocket connection

---

helpers/assets/tools.go

Ginkgo v2 has a dependency on it's own CLI now, eliminating the need to manually import the CLi as a tool.
https://github.com/onsi/ginkgo/releases/tag/v2.8.2
v29.1.0
N/A
None
None

fix(helpers): Remove unnecessary tools import

---

apps/readiness_healthcheck.go
windows/readiness_healthcheck.go

✅ 
This adds a test for the new `audit.app.process.ready` and `audit.app.process.not-ready` events.
* CFF RFC: https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0020-readiness-healthchecks.md
* Tracker story: https://www.pivotaltracker.com/story/show/185799545
* Issue tracking all of the PRs in this effort: https://github.com/cloudfoundry/capi-release/issues/363
* This changes were tested against [capi-release 1.169.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.169.0).
* This capi version is in [cf-deployment v36.0.0](https://github.com/cloudfoundry/cf-deployment/tree/v36.0.0).
Less than …

update readiness health check test to test audit events

---

windows/readiness_healthcheck.go

Fixes the build failure [seen here.](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/windows-cats/builds/938)
[Slack discussion
](https://cloudfoundry.slack.com/archives/C02FM2BPE/p1705951427266359)
release-candidate
0
@ameowlia

Fix windows readiness test

---

assets/service_broker/config.ru
assets/service_broker/service_broker.rb
assets/service_broker/spec/service_broker_spec.rb

Yes
Uses the RewindableInput middleware to recapture a Rack 2 expectation that no longer exists in Rack 3 – that the request.body is rewindable.
Resolves the following error message when curling the `/config` endpoint:
```
undefined method `rewind'
```
- https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cats/jobs/run-cats-vms/builds/240.1
- https://github.com/cloudfoundry/cf-acceptance-tests/pull/1032
v37.0.0
N/A
None
None

fix(assets/service_broker): Use RewindableInput middleware

---

cats_suite_test.go

Yes
Stops output interception from also outputting the result of the `fmt.Println` statement.
Old output:
```
$ ./bin/test -p
Printing sanitized $CONFIG
...
Running CATs with CF CLI version  cf version 8.7.7+583a09a.2023-12-26
...
[SynchronizedBeforeSuite] PASSED [26.126 seconds]
[SynchronizedBeforeSuite]
/Users/lcarson/workspace/cf-acceptance-tests/cats_suite_test.go:69
Captured StdOut/StdErr Output >>
Running CATs with CF CLI version  cf version 8.7.7+583a09a.2023-12-26
<< Captured StdOut/StdErr Output
------------------------------
...
```
v37.0.0
N/A
None
None

chore: Remove duplicated cf CLI version output

---

apps/readiness_healthcheck.go
windows/readiness_healthcheck.go

[The new CATs readiness health check test is somewhat flaky](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/upgrade-cats/builds/937)
* Move the check of the cf eve for readiness health checks until AFTER a different check that has a long timeout.
* We should wait to see that the app is marked ready/not-ready BEFORE we test cf events
none!

Fix flakiness for readiness health check event test

---

apps/lifecycle.go
assets/golang/manifest.yml
assets/logging-route-service/main.go
assets/logging-route-service/manifest.yml
assets/multi-port-app/README
assets/multi-port-app/go.mod
assets/multi-port-app/manifest.yml
assets/pora/manifest.yml
assets/proxy/internal-route-manifest.yml
assets/proxy/manifest.yml
assets/syslog-drain-listener/manifest.yml
assets/tcp-listener/manifest.yml
routing/multiple_app_ports.go

Yes
Specifying Go version in the assets manifests so that apps are deployed with Go 1.21.
None
v33.4.0
N/A
None
@ctlong

fix: Set goversion in app manifests to Go 1.21

---

detect/buildpacks.go

Fix "R" buildpack test. The app needs 2G for staging, lower settings result in "Exit status 223 (out of memory)"
Failed build: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats/builds/935.1
v37.0.0

Increase memory limit for "R" buildpack test

---

README.md

From Ginkgo 1.0 to 2.0, the default timeout for the entire test changed from `24h` to `1h` (refer to: [Ginkgo 2.0 Migration Guide - Timeout Behavior](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#timeout-behavior)).
Depending on the environment in which the test is run, the execution time of the test may exceed 1h, which may cause the test to fail.
Therefore, I have added an explanation regarding the timeout setting for the entire test.

Add overall test timeout setting

---

README.md

I have documented the minimum version of cf cli defined by [`minCliVersion` in `cats_suite_test.go`](https://github.com/cloudfoundry/cf-acceptance-tests/blob/96df8fb4a2c672b3e39eea4dd0a77db99443c6ef/cats_suite_test.go#L47).

Specify the minimum version of cf cli

---

detect/buildpacks.go

Yes
This reverts commit 8d5e5f417549f2bc433d58cbf3b19602d43109e3.
The root cause is most likely a broken stemcell (kernel update caused increased memory consumption).
https://github.com/cloudfoundry/cf-acceptance-tests/pull/1048#issuecomment-1943289724
None
N/A
None
@jochenehret @stephanme

fix(detect): Revert R buildpack memory limit

---

apps/lifecycle.go
windows/lifecycle.go

Adjust regex that "extracts" container metrics from cf-cli output. Memory/disk might be shown as `0B` initially.
Output from a failed CATS run:
```
Regex did not find a match in contents 'Showing health and status for app [...]
[...]
state     since                  cpu    memory       disk       logging        details
#0   running   2024-04-04T10:35:13Z   0.0%   0B of 256M   0B of 1G   0B/s of 0B/s   
'
```

Adjust regex for container metrics

---

cats_suite_test.go

STDOUT output of `fmt` is not captured by ginkgo and thus the version is not printed. When using `GinkgoWriter` the message is captured correctly.
-> not  applicable

Correctly print CF CLI version

---

README.md
bin/test

Yes
Removes references to the log-cache cf CLI plugin from the README.md, as it has not been a dependency of CATs for several years.
f22c80925ae2edb2d92f2d1103cd30e02d928dff.
v40.1.0
N/A
None
None

chore: Remove log-cache cf CLI plugin references

---

assets/credhub-service-broker/config.go
assets/credhub-service-broker/config_test.go
assets/credhub-service-broker/handlers.go
assets/credhub-service-broker/main.go

Yes
Refactors `assets/credhub-service-broker` to use a config struct rather than have various `os.GetEnv` calls & global vars scattered around.
None.
None.
N/A.
None.
None.

Refactor: credhub service broker asset

---

assets/credhub-enabled-app/gradle/wrapper/gradle-wrapper.properties

Yes
Rebuilds the credhub-enabled-app asset, which has had its dependencies bumped but needs to be rebuilt manually.
None
v40.1.0
No
None
None

fix: Rebuild credhub-enabled-app

---

README.md
cats_suite_helpers/cats_suite_helpers.go
example-cats-config.json
helpers/config/config.go
helpers/config/config_struct.go
helpers/skip_messages/skip_messages.go
security_groups/comma_delmited_asgs.go

✅
Adds a test to validate that ASGs with comma delimited destinations function, when configured to do so.
CAPI must be configured to enable this and it is off by default, so the test is also off by default.
Latest.
The functionality requires a combination of CAPI, Diego, cf-networking, and silk to function. This is an integration test across across all the components.
60-200? The time taken to push an app and validate ASG changes to it. 

Add test for comma delimited ASG destinations

---

helpers/config/config_struct.go

Yes
Fixes test failures related to comma delimited ASGs since that feature is opt-in at a bosh manifest level.
Nope
None
Unblocks cf-acceptance-tests CI
@ctlong

Make comma delimited ASG tests off by default

---

credhub/service_bindings.go
credhub/service_keys.go
docker/credhub_enabled.go
route_services/route_services.go

Yes
Fixes an inconsistency in the credhub, docker, and route_services test suites (vs other suites) where apps were not get deleted after tests. Specifically, some service brokers that were pushed as apps were not getting deleted, only unregistered as service brokers.
I ran through some of the steps manually and saw that the delete-service-broker command did not also delete the service broker app.
Spot-checking the credhub suite, I couldn't find any reasons in git or tracker stories for the delete command to not to be originally included. Possibly, it was believed that the delete-service-broker command would delete the app...
v33.4.0
N/A
About the same.
None

fix: Delete service brokers after tests

---

README.md
assets/cnb-node/manifest.yml
assets/cnb-node/package.json
assets/cnb-node/server.js
cats_suite_helpers/cats_suite_helpers.go
cats_suite_test.go
cnb/cnb_lifecycle.go
helpers/assets/assets.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/skip_messages/skip_messages.go

Added acceptance tests using the new cloud native buildpack lifecycle.
* RFC for cloud native buildpacks - https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0028-cnb-lifecycle.md
* Prerequisite 1 - Changes in [cloud_controller_ng](https://github.com/cloudfoundry/cloud_controller_ng/pull/3778)
* Prerequisite 2 - Changes in [diego-release](https://github.com/cloudfoundry/diego-release/pull/929)
* Prerequisite 3 - Changes in [cf-deployment](https://github.com/cloudfoundry/cf-deployment/pull/1178)
* A future version - see …

Add acceptance tests for cnb lifecycle

---

cats_suite_helpers/cats_suite_helpers.go

Prevents race condition when sending a test message to a backend and reading the response.
https://github.com/cloudfoundry/cf-acceptance-tests/issues/1173
v41.0.0
Function is called 7 times -> 700ms.

[Issue 1173] In "SendAndReceive", wait 100ms before reading

---

README.md
assets/binary/go.mod
assets/catnip/go.mod
assets/credhub-service-broker/go.mod
assets/go_calls_ruby/go.mod
assets/golang/go.mod
assets/golang/manifest.yml
assets/grpc/go.mod
assets/http2/go.mod
assets/logging-route-service/go.mod
assets/logging-route-service/manifest.yml
assets/multi-port-app/go.mod
assets/multi-port-app/manifest.yml
assets/pora/go.mod
assets/pora/manifest.yml
assets/proxy/go.mod
assets/proxy/internal-route-manifest.yml
assets/proxy/manifest.yml
assets/syslog-drain-listener/go.mod
assets/syslog-drain-listener/manifest.yml
assets/tcp-listener/go.mod
assets/tcp-listener/manifest.yml
assets/worker/go.mod
go.mod

Yes
* Bump the min Go version required by this module to go1.22.0.
* Bump the min Go version required by Go assets to go1.22.0.
* Bump the Go version specified in Go asset manifests to go1.22.
None
None
N/A
None
None

Bump to go1.22

---

assets/binary/go.mod
assets/catnip/go.mod
assets/credhub-service-broker/go.mod
assets/go_calls_ruby/go.mod
assets/golang/go.mod
assets/grpc/go.mod
assets/http2/go.mod
assets/logging-route-service/go.mod
assets/multi-port-app/go.mod
assets/pora/go.mod
assets/proxy/go.mod
assets/syslog-drain-listener/go.mod
assets/tcp-listener/go.mod
assets/worker/go.mod
go.mod

Yes
Updates assets and base go.mod to use 1.22 as the go directive instead of 1.22.0. Some tooling in buildpacks depends upon the go directive being only in <major>.<minor> format. And it seems like the base go.mod should match.
https://github.com/cloudfoundry/cf-acceptance-tests/commit/043a63ff66b5a67c36a14876edf9095d74b62783#commitcomment-145272348
None
N/A
None
None

Use 1.22 as the go directive instead of 1.22.0

---

assets/binary/go.mod
assets/catnip/go.mod
assets/credhub-service-broker/go.mod
assets/go_calls_ruby/go.mod
assets/golang/go.mod
assets/grpc/go.mod
assets/http2/go.mod
assets/logging-route-service/go.mod
assets/multi-port-app/go.mod
assets/pora/go.mod
assets/proxy/go.mod
assets/syslog-drain-listener/go.mod
assets/tcp-listener/go.mod
assets/worker/go.mod
go.mod

It seems like theres an issue with using `go 1.22.0` with buildpacks as per this commit https://github.com/cloudfoundry/cf-acceptance-tests/commit/a0e5ea36d59c6d7ba56767391ab05bcabe2ca81b .However, the directive `go 1.22` this is not a valid toolchain and so builind the app will result in
```
$ pwd
/Users/sgunaratne/workspace/cf-acceptance-tests/assets/worker
$ go mod tidy
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
```
This adds the toolchain explicitly so work around this issue.
```
$ git diff go.mod
diff --git a/assets/worker/go.mod b/assets/worker/go.mod
index d1180cc5..d3a08650 100644
--- a/assets/worker/go.mod
+++ b/assets/worker/go.mod
@@ -1,3 +1,5 @@
module github.com/cloudfoundry/cf-acceptance-tests/assets/worker
go 1.22
+ …
```

Set go toolchain explicitly

---

assets/pora/Dockerfile

Yes
We want to update the Dockerfile to actually work :)
ARP WG is taking over volume services and revamping a few things, including this.
CATs does not use this dockerfile
We want to keep pora where it is.
0!
@winkingturtlevmw

Update pora Dockerfile to actually compile pora

---

README.md
cats_suite_helpers/cats_suite_helpers.go
helpers/config/config.go
helpers/config/config_struct.go
isolation_segments/isolation_segments.go
windows/tcp_routing.go

Yes
- Make it easier to configure TCP route testing by separating the TCP domains from the apps domain.
- Make it possible to run isolation_segment_routing tests alongside isolation_segment_tcp_routing tests
- Add TCP routing tests for windows
- Improve the output returned by SendAndReceive so that text fits in gomega/ginkgo string length constraints
We discovered issues with tcp routes on cross-deployment scenarios where links weren't properly being configured, and this slipped through testing because of strange nuances to how isolation segment + tcp routes work. Additionally there were no windows tcp route tests
Latest
^^ adds opt-in configuration to cats?
CATs should test the same app/route workloads on windows as it does on isolation segments + primary diego cells
up to two cf push …

Improve TCP Route Testing

---

v3/deployment.go

Yes
* Refactor existing Deployments tests so Rolling deployments use the CLI instead of the API
* Add tests for Canary deployments
* Add tests for max-in-flight
[v42.2.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v42.2.0)
More deployment tests, so more time!

Update Deployment tests

---

assets/binary/site.go
assets/catnip/main.go
assets/credhub-service-broker/main.go
assets/go_calls_ruby/site.go
assets/golang/site.go
assets/logging-route-service/main.go
assets/loggregator-load-generator-go/loggregator-load-generator.go
assets/multi-port-app/main.go
assets/pora/server.go
assets/proxy/main.go
assets/webapp/webapp.go

Yes
Using `Server` struct, which allows specifying a timeout, to create a server in order to address gosec G114
No change to runtime

Use Server struct to address gosec G114

---

helpers/config/config.go
helpers/config/config_struct.go
volume_services/volume_services.go

Add Option for  Volume Service Broker name
If VolumeService Service broker is configured with a different broker-name, cats will fail. With this change, it'll be required to provide a `volume_service_broker_name` only when running volume-services tests
main
N/A
N/A

Add Option for  Volume Service Broker name

---

assets/logging-route-service/.github/dependabot.yml

Removes unnecessary Dependabot config from the logging-route-service since it's already included in the Dependabot config at the base of the repo.
This is just a carry-over from when we used to vendir in this asset from another repo.
https://github.com/cloudfoundry/logging-route-service
None
N/A
None
None

chore(assets/logging-route-service): Remove unnecessary Dependabot config

---

apps/routing_transparency.go

Remove the two problematic characters from Routing Transparency test that should appropriately handles certain reserved/unsafe characters but its not the case.
https://github.com/cloudfoundry/cf-acceptance-tests/issues/1276
v44.0.0

Remove two problematic characters from Routing Transparency test

---

helpers/services/sso.go
security_groups/dynamic_asgs.go

Adapt SSO and ASGs test for a CF deployment with disabled v2 API.
Part of the v2 deprecation story: https://github.com/cloudfoundry/community/pull/941
v44.5.0 with `temporary_enable_v2` set to `false`
No change in runtime behaviour.

Adapt SSO and ASGs test for disabled v2 setup

---

security_groups/comma_delmited_asgs.go

Fix for PR https://github.com/cloudfoundry/cf-acceptance-tests/pull/1312
Remove `/v2/info` endpoint also in comma-delimited security groups test.
v44.6.0
Same as before.

Fix for PR https://github.com/cloudfoundry/cf-acceptance-tests/pull/1312

---

.github/workflows/ci.yml

Yes
Add a GH actions workflow for CI purposes.
None
N/A
N/A
None
None

CI: Add GH actions workflow

---

.github/workflows/build-catnip-docker-image.yml
README.md
assets/catnip/Dockerfile
cats_suite_helpers/cats_suite_helpers.go
file_based_service_bindings/file_based_service_bindings.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go
helpers/skip_messages/skip_messages.go

Acceptance test for file-based service bindings for a Docker app. This PR also includes a GitHub action to build and push a Docker image with the "catnip" test app. The image is uploaded to the github.com package repository:
https://github.com/cloudfoundry/cf-acceptance-tests/pkgs/container/catnip-app
[RFC0030](https://github.com/cloudfoundry/community/issues/901)
v45.0.0 with patched capi-release and diego-release
File-based service bindings will be generally available with an upcoming cf-deployment release.
90 seconds

Docker test for file-based service bindings

---

v3/service_instances.go

The v3 test "Lists the service instances" failed two times in a row because 3 instances were returned, but only 2 expected. Given the current test setup (space is shared between different tests), we cannot guarantee that exactly 2 instances are returned -> use "contain" matcher to relax assertion.
Another possible fix would be to use a separate space for that test.
Failing test runs:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-cats/builds/1842
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/fresh-cats/builds/1841
(none)
No change in runtime.

Fix v3 list service instances test

---

README.md
apps/crashing.go
cats_suite_test.go
helpers/config/config.go
helpers/config/config_struct.go
helpers/config/config_test.go

This change removes the hard coded python buildpack and introduces a configuration variable for it, so it is possible to specify a custom one. As the default stays the same as the currently hardcoded, there should be no compatibility issues.
As stated in the readme, all buildpack names should be customizable and the python buildpack was missing.

Add python buildpack variable

---

.github/dependabot.yml

Yes
Configures Dependabot to create PRs to bump dependencies in our GH actions workflows. This does not affect any of the tests and is purely a CI change.
None
N/A
N/A
None
None

ci(dependabot): Configure GH actions dependencies bumps

---

windows/ssh.go

Yes
The Windows SSH tests do not honour the `include_ssh` config flag.
N/A
N/A
N/A
N/A
@ctlong

Skip Windows SSH tests if include_ssh is not set

---

go.mod
go.sum
vendor/github.com/cloudfoundry/cf-test-helpers/v2/helpers/internal/curl.go
vendor/modules.txt

Yes
Bump cf-test-helpers to 2.11.0.
https://github.com/cloudfoundry/cf-test-helpers/releases/tag/v2.11.0
N/A
N/A
N/A

Bump cf-test-helpers to 2.11.0

---

README.md
go.mod

Yes
Updating the minimum required version of Go to go1.23.0.
If any dependencies of a module require a minimum version of Go that is greater than the minimum version of Go required by the module, then `go mod tidy` will update the minimum version of the module. This is what was happening when I ran `go mod tidy`. I've simply committed the result of that command.
v48.3.0
N/A
None
None

fix: Bump the minimum required version of Go to go1.23.0

---

assets/binary/go.mod
assets/catnip/go.mod
assets/credhub-service-broker/go.mod
assets/go_calls_ruby/go.mod
assets/golang/go.mod
assets/golang/manifest.yml
assets/grpc/go.mod
assets/http2/go.mod
assets/logging-route-service/go.mod
assets/logging-route-service/manifest.yml
assets/multi-port-app/go.mod
assets/multi-port-app/manifest.yml
assets/pora/go.mod
assets/pora/manifest.yml
assets/proxy/go.mod
assets/proxy/internal-route-manifest.yml
assets/proxy/manifest.yml
assets/syslog-drain-listener/go.mod
assets/syslog-drain-listener/manifest.yml
assets/tcp-listener/go.mod
assets/tcp-listener/manifest.yml
assets/worker/go.mod

Yes
Bumps the minimum Go versions of all the Go assets to `1.23`, omitting the patch version due to handling issues with the Go buildpack in certain edge cases.
- https://github.com/cloudfoundry/cf-acceptance-tests/commit/043a63ff66b5a67c36a14876edf9095d74b62783#commitcomment-145272348
- https://github.com/cloudfoundry/cf-acceptance-tests/pull/1195
v48.4.0
N/A
None
None

fix(assets): Bump minimum Go version to 1.23

---

bin/test

Yes i did it right this time!
Ginkgo v2 changed the default suite timeout to 1hr which is too short for cats.
We recommend people set it to 24h in the readme
cats ref 562033f1  + cf-d v44.9.0

update default suite timeout to 24h, as ginkgov2 changed it to 1h

---

assets/pora/server.go

since go 1.20 rand has been automatically seeded
Yes
Calling rand.Seed globally is no longer needed. Since go 1.20 rand has been automatically seeded. go 1.20 was released in Feb 2022 and is no longer supported.
* https://pkg.go.dev/math/rand@go1.20#Seed
n/a
micoseconds faster!

remove unnneeded global rand.Seed logic

---

routing/process_routing.go

* X-CF-PROCESS-INSTANCE:<process_guid>
* X-CF-PROCESS-INSTANCE:<process_guid>:<instance_index>
**note** This should not be merged until the work has been complete in GoRouter and released in cfd.
Yes
Add CATs test for ability to route to a specific process and process instance.
* https://github.com/cloudfoundry/gorouter/pull/467/files
* https://github.com/cloudfoundry/cf-deployment/releases/tag/v48.7.0
```
Ran 1 of 250 Specs in 136.660 seconds
SUCCESS! -- 1 Passed | 0 Failed | 2 Pending | 247 Skipped
PASS | FOCUSED
```

Add X-CF-PROCESS-INSTANCE header tests for routing

---

v3/deployment.go

Adds test for Canary steps.
* CAPI change: https://github.com/cloudfoundry/cloud_controller_ng/pull/4219
* CF CLI change: https://github.com/cloudfoundry/cli/pull/3390
* [v48.5.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v48.5.0)
Integration of CF CLI and CAPI.
~2mins

Add canary instance step test

---

cnb/cnb_lifecycle.go

Yes
With the current dev-release of CAPI, this test is no longer valid.  You can push an app without specifying a particular buildpack, as CNBs now have a system support (and with that, buildpack detection)
We are still working on replacing this with more extensive acceptance tests.
You can see where we removed the error: https://github.com/cloudfoundry/cloud_controller_ng/pull/3898/files#diff-1c0ac13c424df7993b1515f0f18b2b3358a1889688c0aa22c62381a3b3a7c7c9L492
n/a, this is for a pre-release CAPI.

Skip outdated CNB test

---

README.md
helpers/config/config_struct.go

Yes.
We change the registry for Cloud Native Buildpacks from gcr.io to docker.io.
Paketo stopped providing images on gcr.io. See [blog](https://blog.paketo.io/posts/paketo-gcr-registry-sunset/).

Change CNB registry to docker.io

---

assets/golang/site.go
ipv6/ipv6.go

Yes.
The change is part of the ipv6 egress validation cycle. We progressively extend all of the exciting buildpacks relevant to our ecosystem.  In this PR we provide additional endpoints in the Golang application for testing IPv6 support. In case ipv6 validation is enabled, we verify that egress ipv6 call are possible with Go applications. 
https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0038-ipv6-dual-stack-for-cf.md
v48.9.0
_CATs should validate IPv6 egress calls with Golang application. We add changes regarding to this buildpack only. The test group for ipv6 was already created.
Around 90 seconds per test.
@oliver-heinrich @iaftab-alam

Ipv6 validation for Golang

---

route_services/route_services.go

There were some left overs from  [PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/1564). This PR aim to fix this.
The existing go lang app was changed with this [PR](https://github.com/cloudfoundry/cf-acceptance-tests/pull/1564) that introduces new group and made changes to already existing check, which needs to be propagated where is is consumed.
N/A
N/A

Fix left overs from PR#1564

---

assets/service_broker/README.md
assets/service_broker/data.json
assets/service_broker/run_all_cases.rb
bin/catsconfiggenerator/main.go
helpers/config/config_test.go

Yes.
Adjust bosh-lite domain to "bosh-lite.env.wg-ard.ci.cloudfoundry.org"
CATs unit tests ([run-unit-tests](https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/cats/jobs/run-unit-tests)) are currently failing due to [bosh-lite.com](http://bosh-lite.com/) was shut down.
An A record *.[bosh-lite.env.wg-ard.ci.cloudfoundry.org](http://bosh-lite.env.wg-ard.ci.cloudfoundry.org/) is added to our DNS zone.
N/A
N/A

Adjust bosh-lite domain

---

README.md
cnb/cnb_lifecycle.go
helpers/assets/assets.go

Yes
New system CNB feature 
https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0031-system-cnb.md
https://github.com/cloudfoundry/cloud_controller_ng/pull/4342
[v49.0.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v49.0.0), but you need pre-release CF CLI
Tests basic system CNB workflow
120s
Currently blocked on CLI release

Add test for uploading system CNB

---

file_based_service_bindings/file_based_service_bindings.go
file_based_service_bindings/life_cycles.go
helpers/services/service_helper.go
ssh/ssh.go
windows/ssh.go

Test app features specified in the manifest.
https://github.com/cloudfoundry/cloud_controller_ng/pull/4358
v49

Features in manifest
