cloudfoundry/cf-acceptance-tests

- apps/admin_buildpack_lifecycle_test.go
- apps/droplet_download_test.go
- apps/dynamic_info_test.go
- apps/init_test.go
- apps/lifecycle_test.go
- apps/process_types_test.go
- assets/dora/dora.rb
- assets/node-with-procfile/app.js
- assets/node/server.js
Also tagged some tests that won't be compatible as of this commit (or any time soon in `cf files`'s case) so we can filter them out via the BOSH errand.
Each commit should provide a bit more detail.
> A slew of changes to make CATs more compatible with Diego

- detect/buildpacks_test.go
We've had no insight into some flakey tests and would like to expose more information.
Signed-off-by: JT Archie <jtarchie@gmail.com>
> logs failures of apps that failed staging [#103840940]

- apps/admin_buildpack_lifecycle_test.go
> Don't delete app file in admin buildpack test

- assets/ruby_simple/Gemfile
Remove reference to Ruby version no longer supported by buildpacks.
> Update ruby_simple Gemfile

- README.md
- apps/healthcheck_test.go
- apps/instance_reporting_test.go
- assets/worker-app/Godeps/Godeps.json
- assets/worker-app/Procfile
- assets/worker-app/main.go
- backend_compatibility/backend_compatibility_test.go
- docker/docker_lifecycle_test.go
- helpers/assets/assets.go
- ssh/ssh_test.go
https://www.pivotaltracker.com/story/show/111125958
> Continuing CATS absorb DATS

- routing/context_paths_test.go
- routing/route_services_test.go
- routing/routing_suite_test.go
- routing/session_affinity_test.go
This PR addresses GH issues both https://github.com/cloudfoundry/cf-acceptance-tests/issues/86 and https://github.com/cloudfoundry/cf-acceptance-tests/issues/87:
- Fix tests so they delete app properly
- Add missing app logging for session affinity tests
Note, talked to Amit and he was ok with a single PR for two issues, since the changes were in same area.
@markstgodard && @chavdarch
> Routing CATs fixes for GH issues: #86 and #87

- apps/loggregator_test.go
This commit checks that the container metrics have been submitted for the specified application.
[#113279137]
Signed-off-by: Sandy Cash <scarlet.tanager@gmail.com>
> Add test to verify container metrics

- ssh/ssh_test.go
Updated the test to check if STDERR is also copied across from a ssh session.
[#112308797]
Signed-off-by: Connor Braa <cbraa@pivotal.io>
> ssh test checks that we properly copy stderr

- docker/docker_lifecycle_test.go
* Previously, $HOME would also be "app" and $TMPDIR would always be "app/tmp"
* With this change, if either of these variables were set with 'cf set-env', we use that value for the variable. Otherwise, we use the value of the variable defined in the Dockerfile, if set. Otherwise, $HOME will be set to the system default (from /etc/passwd) and $TMPDIR will remain unset.
[#122608871]
Paired with @caod123
> Update docker test to reflect new env var behavior

- helpers/services/sso.go
This is an upcoming change to the UAA
This change is backwards compatible
> Add csrf cookie to UAA's /oauth/authorize UI HTML form

- apps/admin_buildpack_lifecycle.go
Tracker story: https://www.pivotaltracker.com/story/show/118213487
Signed-off-by: Greg Cobb <gcobb@pivotal.io>
Signed-off-by: Michael Xu <mxu@pivotal.io>
> Stop skipping admin buildpack tests on diego

- security_groups/running_security_groups.go
We're backfilling test coverage for ASGs on running apps.  The existing test coverage is not agnostic to the presence/absence of [container networking](https://github.com/cloudfoundry-incubator/netman-release).
How we ended up with the current approach:
- The test must target an IP that is not whitelisted by existing security group rules
- We cannot reliably learn the IP of a real network endpoint that meets this requirement
- Therefore we use a nonsense IP, and assert on the particular error code returned by a `curl` command attempting to reach that IP
- When whitelisted, the exit code is typically a timeout
- When not whitelisted, the exit code is `7: Failed to connect to host`
The exit-code assertion is fragile: it may fail if the user's network is configured abnormally.  But the other …
> Running Security Groups coverage for connecting to non-container destinations

- apps/droplet_uploading_and_downloading.go
This PR is to fix the flakiness in the "Uploading and Downloading droplets" test introduced by PR #145.
> Fix flakiness app droplet test

- security_groups/running_security_groups.go
This behavior is no longer supported by ASGs. Inter-container communication is only supported with the container networking feature.
We previously added test coverage for containers communicating to non-containers here: https://github.com/cloudfoundry/cf-acceptance-tests/pull/150
This test needs to be removed for CATS to run successfully in environments that are rolling out container networking to some but not all cells.
cc @mcwumbly 
https://www.pivotaltracker.com/story/show/135541215
> Remove legacy asg test for inter-container communication

- apps/lifecycle.go
> add assertion for `CF_INSTANCE_INTERNAL_IP`

- apps/admin_buildpack_lifecycle.go
**One of these tests will fail until the changes from the below bug make it into cf-release**
- Backfill test for happy path
- Add test for specifying a disabled buildpack. This was a regression introduced by the change to Diego
Tracker Story: https://www.pivotaltracker.com/story/show/134620921
> Add CATs for specifying specific buildpack

- README.md
- security_groups/running_security_groups.go
- clarify the relationship between some of the test groups
> Update the README.

- README.md
https://github.com/cloudfoundry/cf-acceptance-tests/issues/177
> fix sample config for us copy-and-pasters

- isolation_segments/isolation_segments.go
- Test depends on isolation segment to exist on CC. If the segment does
not exist, create one in the before and delete after the test run.
https://www.pivotaltracker.com/story/show/138963697
Signed-off-by: Eric Promislow <eric.promislow@hpe.com>
> Create iso seg if it doesn't exist

- security_groups/running_security_groups.go
Replace soon-to-be deprecated `deny-access` with `remove-access`
@jaydunk
> change network policy plugin command

- helpers/skip_messages/skip_messages.go
- security_groups/running_security_groups.go
- add skip message to skip_messages
> Skip ContainerNetworking needed test in beforeEach

- README.md
> added missing test groups to config file generation script

- apps/default_environment_variables.go
Fixes #218
The test previously would only get recent logs once and assert that the environment variables are in the logs, however sometimes it can take a second or two longer for those logs to show up. This change will pull `logs --recent` until it finds one of the environment variables or hits the default timeout.
@enocom
> Fix default variables test only getting recent logs once

- README.md
Signed-off-by: Alex Melnik <aleksandr.melnik@suse.com>
related: cloudfoundry/cats-concourse-task#7
> added documentation around container-networking tests

- apps/loggregator.go
This is to help ensure that container metrics are properly getting their values populated.
Signed-off-by: Brady Love <blove@pivotal.io>
> Check containerMetrics are non-zero in firehose test

- security_groups/running_security_groups.go
[#149968586]
Signed-off-by: Dennis Leon <dleon@pivotal.io>
> Use new cli network commands, not plugin commands

- assets/credhub-service-broker/main.go
- cats_suite_helpers/cats_suite_helpers.go
- docker/credhub_enabled.go
- helpers/skip_messages/skip_messages.go
> add CATs to ensure dockerapplifecycle launcher integrates properly with credhub

- services/service_instance_lifecycle.go
This is a backwards compatible change, so merging it in now won't break anything.
- Related to https://www.pivotaltracker.com/story/show/126256747
> adjusting tests to work with upcoming refactor of service command

- credhub/service_bindings.go
See context here: https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1509390357000353
> Avoid messing with detection buildpacks

- helpers/download/download.go
Solves the same problem as #155.
> Include protocol in download URLs.

- tasks/task.go
Per a conversation between Rel-Int and Networking, we have added test coverage that was previously lacking. The new task test checks that policies apply to tasks.
[#155527928]
Signed-off-by: Tyler Schultz <tschultz@pivotal.io>
> Add task connectivity test

- assets/proxy/README.md
- assets/proxy/handlers/download_handler_test.go
- assets/proxy/handlers/stats_handler_test.go
- assets/proxy/handlers/upload_handler_test.go
- assets/proxy/integration/integration_suite_test.go
- assets/proxy/main.go
- security_groups/running_security_groups.go
- Both asgs and container networking are core networking features
[#155527932]
Signed-off-by: Angela Chin <achin@pivotal.io>
> Update running-security-group and container networking test to be one

- apps/default_environment_variables.go
- vendor/code.cloudfoundry.org/cf-routing-test-helpers/helpers/apps.go
- windows/http_healthcheck.go
- windows/running_log.go
- windows/set_start_command.go
- windows/ssh.go
- windows/worker.go
[#156235680]
Signed-off-by: Brady Love <blove@pivotal.io>
> Use log cache if enabled for windows CATS

- windows/instance_reporting.go
We're seeing the windows instance reporting specs fail with the following error. Not sure what caused the breakage, but making the test more similar to the `apps/instance_reporting.go` test has resolved the problem for us. Possibly related to a switch to go 1.10 in our pipelines.
```
[windows] Getting instance information scaling memory beyond the available amount [It] fails with insufficient resources 
/tmp/build/33ac16d1/go/src/github.com/cloudfoundry/cf-acceptance-tests/windows/instance_reporting.go:55
Got stuck at:
Showing health and status for app CATS-1-APP-f75554cb5e07d8ec in org CATS-1-ORG-8621f09246baa562 / space CATS-1-SPACE-ede9ebe9035b6d2d as CATS-1-USER-f87d069a567b368a...
name:              CATS-1-APP-f75554cb5e07d8ec
requested state:   started
routes: …
```
> Fix text matching to be similar to the non-windows instance reporting tests

- windows/running_security_groups_win.go
Yes
`windows/running_security_groups_win.go` accesses the internet, we've updated it to only do the internet access when `GetIncludeInternetDependent` is true
custom version with latest component versions
n/a, simple test refactor
n/a
> Update windows test to respect 'include_internet_dependent'

- services/service_instance_lifecycle.go
Update service binding tests to use the CF CLI instead of `cf curl`. This new test is designed to work with both the current wording and the updated wording introduced in https://github.com/cloudfoundry/cli/pull/1452.
https://www.pivotaltracker.com/story/show/159168130
no change
@georgi-lozev
> Use CF CLI to create and delete service bindings

- isolation_segments/isolation_segments.go
[#160797350]
Signed-off-by: Travis Patterson <tpatterson@pivotal.io>
yes
Adds test for cf logging system
- https://github.com/cloudfoundry/cf-deployment/pull/624
- https://www.pivotaltracker.com/n/projects/1382120/stories/160692783
- https://www.pivotaltracker.com/story/show/160797350
5.1
Release-integration requested a test for new logging system changes
- Adds test for isolated CF logging system
negligible 
@apoydence @jtuchscherer
> adds logging tests for isolation segments

- README.md
- helpers/config/config.go
- helpers/config/config_struct.go
- helpers/skip_messages/skip_messages.go
- v3/deployment.go
This change is being made in service of GA'ing the deployments API and inlining the cc_deployment_updater process into cf-deployment.yml
associated cf-deployment promotion: https://github.com/cloudfoundry/cf-deployment/pull/701
https://www.pivotaltracker.com/story/show/161238989
7.0.0
The promoted test is optional for now, but that flag could be removed some time after after cf-deployment has inlined the deployment_updater
Today CATs need to be able to validate that the zero-downtime pushes work and that cc_deployment_updater has been deployed correctly
Future CATs need to validate that operators have deployed a CF that …
> promote deployment CAT from capi_experimental to v3

- assets/multi-port-app/README
This app is recommended as a sample in docs for the Custom App Ports feature https://docs.cloudfoundry.org/devguide/custom-ports.html
_Something brief that conveys the change and is written with the component author audience in mind._
> Adding a README

- assets/nora/README.md
Yes
Improving documentation.
There was no list of the endpoints Nora accepts (similar to [Dora's README](https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/assets/dora/README.md)).
No tests needed as it's only a documentation change
Improved Nora documentation
0!
> Add a list of endpoints to Nora's README

- volume_services/volume_services.go
The volume services test in CATs requires a shared domain and we were not creating this as part of the test setup.
So, this commit fixes that.
[#169354687](https://www.pivotaltracker.com/story/show/169354687)
Release candidate
Improve the repeatability of the volume services test in CATs by creating the required shared domain during test setup.
The time difference is negligable
cc/@julian-hj, @DennisDenuto uto, @lcho
> Ensure test creates the shared domains that it requires

- assets/nora/README.md
Info for bosh windows stemcell users
Trivial readme change
_Something brief that conveys the change and is written with the component author audience in mind._
> assets/nora: Add info to Readme

- apps/loggregator.go
- windows/metrics.go
Remove flaky loggregator v1 metrics tests
https://cloudfoundry.slack.com/archives/C02HCCXV5/p1585160921007600
cf deployment master
Option 4: Deletes a test
> remove flaky metrics test

- apps/admin_buildpack_lifecycle.go
- apps/app_stack.go
- apps/app_staging_environment.go
- apps/buildpack_cache.go
- apps/changing_start_command.go
- apps/crashing.go
- apps/default_environment_variables.go
- apps/delete_route.go
- apps/droplet_uploading_and_downloading.go
- apps/environment_variables_group.go
- apps/instance_reporting.go
- apps/large_payload.go
- apps/lifecycle.go
- apps/loggregator.go
- apps/output_volume.go
- apps/piecemeal_app_creation_flow.go
- apps/routing_transparency.go
- apps/syslog_drain.go
- apps/wildcard_routes.go
- cats_suite_helpers/cats_suite_helpers.go
- credhub/service_bindings.go
- docs/run-on-k8s.md
- helpers/app_helpers/app_helpers.go
- helpers/skip_messages/skip_messages.go
- security_groups/running_security_groups.go
- v3/buildpacks.go
Updating CATS (app suite) to work with CF on Kubernetes.
https://www.pivotaltracker.com/story/show/174257193
It is now possible to run a subset of CATS against a CF on Kubernetes!
@Syerram @jamespollard8
> 174257193 cats continued

- services/service_instance_lifecycle.go
Yes
When no service key is found, CLI v7 and earlier printed an error
message to STDOUT. v8 and above with print it to STDERR as this is the
standard for refactored commands. The test has been update to accept
either.
Additionally a lint error with the name of ASYNC_OPERATION_POLL_INTERVAL
was fixed by changing it to asyncOperationPollInterval, and an unchecked
error is now checked.
None needed
v13.6.0
No
Update service keys test for CF CLI v8
zero
> service keys: allow error message on STDERR

- route_services/route_services.go
Reverts cloudfoundry/cf-acceptance-tests#452
> Revert "Add new cat for route service with sticky sessions"

- helpers/services/sso.go
- services/sso_lifecycle.go
Yes
The nil checks weren't testing anything and misleading users when they should have failed
https://cloudfoundry.slack.com/archives/C03FXANBV/p1612218204015600?thread_ts=1612201884.012700&cid=C03FXANBV
latest
@peterhaochen47 @thausler786
> invalid nil checks

- helpers/cli_version_check/cli_version_check_test.go
Yes
Correct 2 spelling errors
N/A
17.1.0
- [x ] N/A
N/A
No release notes description required
none
- [ x] **Slightly Less than Urgent**
N/A
> 2 minor spelling errors

- helpers/app_helpers/app_usage_events.go
- helpers/v3_helpers/v3.go
Yes
Fixes some struct tags that weren't properly formatted.
N/A
None
No.
N/A
N/A
N/A
> Fix json struct tags and export pagination href

- PULL_REQUEST_TEMPLATE.md
Yes
Remove question asking for a release note, as we're going to start using the Github-generated release notes for the most part.
**Note: this means we care more about PR titles!!**
N/A
N/A
N/A
N/A
@davewalter
> Update: PULL_REQUEST_TEMPLATE.md

- assets/proxy/main.go
Yes
The Dynamic ASG test pushes an app that attempts to communicate with Cloud Controller via its internal IP address, but it doesn't trust the certificate that CC presents. This change will tell the app to not attempt to validate the certificate when making the request.
See #501 for more details.
CF v19+
N/A
N/A
@ctlong
> Update proxy app to skip TLS verification

- helpers/services/broker.go
Update to #593. Without these changes we see these errors on environments that have self signed certs:
```
Summarizing 3 Failures:
[PANICKED!] [services] SSO Lifecycle [BeforeEach] When a service broker is updated with a new dashboard client can perform an operation on a user's behalf using sso
/usr/local/go/src/runtime/panic.go:220
[PANICKED!] [services] SSO Lifecycle [BeforeEach] When a service broker is deleted can no longer perform an operation on a user's behalf using sso
/usr/local/go/src/runtime/panic.go:220
[PANICKED!] [services] SSO Lifecycle [BeforeEach] When a service broker is created with a dashboard client can perform an operation on a user's behalf using sso
/usr/local/go/src/runtime/panic.go:220
```
> Update new broker GetApiInfoUrl to support SkipSSLValidation config flag

- README.md
- bin/run_units
- bin/test
- bin/update_submodules
Updates bin scripts.
None
N/A
N/A
None
None
> Update: bin scripts

- ci/pipeline.yml
Use ARD WG Git Bot for git/github authentication.
> Use ARD WG Git Bot

- .github/dependabot.yml
Yes
Keeping assets' dependencies up-to-date.
None
N/A
N/A
None
None
> CI: Update Dependabot configuration

- security_groups/dynamic_asgs.go
I did! Look! I actually did this time on the first try!
NCP configures the NSX-T firewalls to drop by default, rather than reject, like what silk does. We should allow for both error cases in our tests.
Additionally, NSX-T firewalls do not support `10.0.0.0/0` as a valid CIDR block. We updated the ASG rules to provide 3 sets of internal private address space to achieve the same goal. 
Discovered while validating CF functionality against an NCP + NSX-T environment.
None, not applicable (TAS)
No new tests
No change in runtime.
> Update ASG tests to work with the NCP/NSX-T CNI

- README.md
yes
Update readme with correct default run test groups. See https://github.com/cloudfoundry/cf-acceptance-tests/blob/main/helpers/config/config_struct.go#L161
> Update README.md with correct default test groups

- route_services/route_services.go
Yes
Deletes the app when we're still targeting the correct org so that the deletion succeeds.
#1152 
v40.15.0
N/A
None
None
> fix: route_services error deleting app

- assets/catnip/file/file.go
- assets/catnip/router/router.go
- file_based_service_bindings/file_based_service_bindings.go
- file_based_service_bindings/life_cycles.go
- services/service_broker_lifecycle.go
- windows/file_based_service_bindings.go
Yes
Simply updates some outdated import statements. This will not change functionality.
None
None
N/A
None
None
> chore: Update import statements
